### PR TITLE
@ledgerhq/live-common@21.33.0 + enable Algorand

### PR DESCRIPTION
**Pull request by gre**
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.33.0

---

- LL-9216 be less strict on breaking on non user accounts
- LL-9196 Update vtc explorer url
- LL-9198 crypto-assets list update
- LIVE-1123: low amount user shouldn't be able to set everything he want
- LIVE-825 - Update market API to have an AND logic on filters instead of OR logic 
- LIVE-1186 Update Polkadot Nano app min version to v10.9160.1 
- LIVE-1338 Remove Algorand JS impl from experimental mode
- LIVE-1337 Add check for recipient not equal to sender on crypto.org 
- LIVE-886 (Market): add sparkline variation + fix issue in countervalues 

---

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by henrily-ledger** [comment]
If this PR is CI greened : 
https://github.com/LedgerHQ/ledger-live-desktop/pull/4790
We will probably need to rebase it above this one, otherwise windows wont work with Polkadot bump :(

**Review by nabil-brn — APPROVED** [review]
✔️  Tested

---
b1f4c73e4 (HEAD -> live-common-21-33-2, ledger/live-common-21-33-2) trigger ci

**Pull request merged**
