### PR TITLE
remove text when button is in loading state

### PR DESCRIPTION
**Pull request by valpinkman**
### Type

UI Fix

### Parts of the app affected / Test plan

Screen Recording 2020-02-26 at 15 14 04

### CODE REVIEW

**Comment by gre** [comment]
this solution is not ideal and was previously discarded by Design because the button width blinks.

**Comment by gre** [comment]
it would be great to make a gif of all diff possibility :
- the existing one
- your approach
- a variant version of the approach which would guarantee the width don't change (we can use opacity and keep absolute centering)

can you try the 3rd option? @valpinkman

**Comment by juan-cortes** [comment]
> it would be great to make a gif of all diff possibility :
> 
> * the existing one
> * your approach
> * a variant version of the approach which would guarantee the width don't change (we can use opacity and keep absolute centering)
> 
> can you try the 3rd option? @valpinkman

That third option is literally what we used to have, the version I did hid the text and showed the spinner. We had that on production for some time I'm 92% sure of it :trollface:

**Comment by valpinkman** [comment]
## Existing
CleanShot 2020-02-26 at 17 51 38

## Proposal 1
Screen Recording 2020-02-26 at 15 14 04

## Proposal 2
CleanShot 2020-02-26 at 17 47 58

**Comment by juan-cortes** [comment]
Please let's just go back to proposal 2 for my mental health's sake.

**Comment by valpinkman** [comment]
> Please let's just go back to proposal 2 for my mental health's sake.

Proposal 2 is accepted by @aramab

**Comment by gre** [comment]
works fine. this really feels great btw.

**Pull request merged**
