### PR TITLE
update device connect imports

### PR DESCRIPTION
**Pull request by valpinkman**
- removed the DeviceConnect logic from desktop and moved it to live-common
- Updated live-common to use the DeviceConnect logic from live-common

### Type

Code Improvement

### Context

LL-2223

### Parts of the app affected / Test plan

Everywhere DeviceConnect is used (manager, txs, add account....)

### CODE REVIEW

**Comment by gre** [comment]
I'm setting a HODL because I think https://github.com/LedgerHQ/ledger-live-desktop/pull/2661 needs to go first as the 12.2.1 came with some changes for Manager (not that it would be breaking but still great to bump in order)

**Comment by gre** [comment]
@valpinkman can you rebase? why is it HODL?

**Comment by gre** [comment]
@valpinkman sorry to ask again but you can rebase again (and probably squash into one commit), you no longer need to say "bump live common" because 12.5.0 is now on develop 🚀

**Comment by valpinkman** [comment]
Will do @gre

**Pull request merged**
