### PR TITLE
Insert variable currencyName in error message

### PR DESCRIPTION
**Pull request by dasilvarosa**
Variable got erroneously replaced by Bitcoin.

### Type

Wording fix

### CODE REVIEW

**Comment by dasilvarosa** [comment]
I'm testing... HODL

**Comment by dasilvarosa** [comment]
All good.

image

**Comment by meriadec** [comment]
omg is it for real

**Comment by dasilvarosa** [comment]
Yeah, I copy-pasted a wording from mobile project to align but without correcting it. :sorry:

**Comment by meriadec** [comment]
Ah ok :sweat_smile: so it's not here from the beginning !
I think we should also use variable for this, right?

**Pull request merged**
