### PR TITLE
LL-5215 (No-Countervalue): add tooltip on placeholder in case of no available countervalue

### PR DESCRIPTION
**Pull request by LFBarreto**
(No-Countervalue): add tooltip on placeholder in case of no available countervalue
### Type

UI Polish
### Context

[LL-5215]
### Parts of the app affected / Test plan

Countervalues in app should show a tooltip in case of missing data

[LL-5215]: https://ledgerhq.atlassian.net/browse/LL-5215

### CODE REVIEW

**Review by juan-cortes — DISMISSED** [review]
lgtm

**Review by JunichiSugiura — CHANGES_REQUESTED** [review]
Accept new snapshots if it's appropriate

**Comment by juan-cortes** [comment]
Lint is complaining now @LFBarreto + the flaky test for swap, still has the autohighlight nonsense on the To selector 🤕

**Review by stual-ledger — CHANGES_REQUESTED** [review]
Heya :)
Unfortunately the wording doesn't display, either in the Portfolio view, the Account view, or in the detail account in both :( see screenshots below 

Reference # for the commit tested : `e58d6b3d4f50f76ecdc3e739a95ad16149539c45`

Screenshot 2021-08-09 at 15 40 17
Refere
Screenshot 2021-08-09 at 15 40 05
nce commit when tested : `e58d6b3d4f50f76ecdc3e739a95ad16149539c45`
Screenshot 2021-08-09 at 15 40 27

**Comment by stual-ledger** [comment]
lgtm 🚀 
Screenshot 2021-08-30 at 15 05 02

**Review by stual-ledger — DISMISSED** [review]
lgtm 🚀 
Screenshot 2021-08-30 at 15 05 02

**Comment by valpinkman** [comment]
@LFBarreto please fix screenshots

**Review by machard — DISMISSED** [review]

**Review by valpinkman — DISMISSED** [review]

**Pull request merged**
