### PR TITLE
LL-7073 change CTAs on the account page to always include SEND/RECEIVE

### PR DESCRIPTION
**Pull request by LFBarreto**
## 🦒 Context (issues, jira)

[LL-7073]

## 💻  Description / Demo (image or video)

[**Figma for reference**](https://www.figma.com/file/ud9Zpy1doMsgxtuxH8RxJo/LLD---Account?node-id=1871%3A61326)

- Send/Receive CTAs are now always displayed (when available) vs. previously if buy/swap was available the send/receive CTAs were only displayed in the dropdown.
- I also fixed the logic to decide whether "swap" CTA should be available as the existing logic depended on swap v1 so it wasn't working anymore.
- **The buttons now fade in altogether the first time they appear**: this is due to the logic for deciding whether to display the "swap" button being **asynchronous**. If we don't do this fade in, their is a risk for click jacking because of the sudden apparition of the swap button.
- Change style of all buttons: rounded with no text, label shows in tooltip instead
- Remove dropdown, replaced it by normal buttons on the same row
- Remove buttons rendered by specific families' `AccountHeaderActions` or they would show up twice (as the content is the same as for the "manage" dropdown, cf. previous line)

https://user-images.githubusercontent.com/91890529/144594331-e1371dd9-f1a0-4f4a-be36-40331321edb3.mov

Combined

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

[LL-7073]: https://ledgerhq.atlassian.net/browse/LL-7073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ofreyssinet-ledger** [comment]
**Do not merge before QA please**

**Review by valpinkman — DISMISSED** [review]

**Review by OlivierFreyssinet — DISMISSED** [review]
approved by @LFBarreto I swear

**Review by ghost — COMMENTED** [review]
Looks good to me overall, but I have a quick question / feedback.

For Cosmos, we have a staking feature, the button is not visible anymore in the new version. In the last version it was visible but disabled (because not enough funds).

Before
before

After
after

Is it normal/expected?

**Comment by ofreyssinet-ledger** [comment]
It should be good now @achabrolin-ledger.

This will do the job for now I think but I'll update when I get the feedback from the design team.

Screenshot 2021-12-07 at 15 18 56

**Review by valpinkman — APPROVED** [review]

**Review by ghost — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]

**Review by thomasrogerlux — APPROVED** [review]

**Pull request merged**
