### PR TITLE
LIVE-1569 Add "Hide NFT Collection" feature

### PR DESCRIPTION
**Pull request by grsoares21**
## 🦒 Context (issues, jira)
This feature allows the user to hide NFT collections. The hidden NFT collections are saved as part of the user's settings and can be unhidden in the settings page under the "Accounts" tab.
[LIVE-1569]

## 💻  Description / Demo (image or video)
nft-hide-collection

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

[LIVE-1569]: https://ledgerhq.atlassian.net/browse/LIVE-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gre — COMMENTED** [review]
any way we can cover this with test automation?

**Comment by grsoares21** [comment]
> any way we can cover this with test automation?

Probably, yes, but depends on the NFT mocks and tests that @aulric-ledger was working on. I'll check with him what we have and what we can add

**Comment by grsoares21** [comment]
Closed due to wrong branch name according to the process. New PR is being made.

**Pull request closed without merging**
