### PR TITLE
Improve crash screen design and behaviour

### PR DESCRIPTION
**Pull request by meriadec**
2018-06-20_968x599

### CODE REVIEW

**Comment by meriadec** [comment]
Ye I know :/ design don't include it, but you're right we can put it anyway (like hard reset button :p)

**Comment by meriadec** [comment]
2018-06-20_892x699

**Comment by gre** [comment]
sounds good. i hope people won't send us this screenshot without the expanded Show Error 🤣 i would prefer to see everything... i wonder what design thing . anyway it's ok for now

**Comment by gre** [comment]
it's ok for now, let's merge this

**Comment by meriadec** [comment]
We can't prevent people from being stupid

**Pull request merged**
