### PR TITLE
Fix not seeing legacy ETC address (derivated from ETH path)

### LINKED ISSUE #945: Missing Ethereum Classic app
#### Ledger Live Version and Operating System

- Ledger Live **1.0.0**
- Platform: **Windows 10**

#### Expected behavior

Unlock/get into ETC wallet

#### Actual behavior

Client says open ETC app, there is no app. 

#### Steps to reproduce the behavior

Tried with ETH app, not working.

### LINKED ISSUE #946: Ethereum Classic currently don't scan legacy account that was created pre-fork
#### Ledger Live Version and Operating System

- Ledger Live **1.0.0**
- Platform: **mac**

### PR DESCRIPTION
**Pull request by gre**
Fixes #946 
Fixes #945

### CODE REVIEW

**Comment by stokla** [comment]
Hi, I hope I am right here.
I can not add my ETH account to Ledger Live.
I open "Add accounts", my Ledger already was connected and unlocked, then I open the ETH App on my Ledger Nano S but on Ledger Live i got not connected (see picture).
With an LTC account it works well.
I run Ledger Live 1.0.1 on Windows 10

image

**Comment by meriadec** [comment]
hey @stokla , you may [open an issue](https://github.com/LedgerHQ/ledger-live-desktop/issues/new/choose), and add as much information you can (logs, device version, app version, etc). also, makes sure you don't have browser support enabled for eth app.

**Comment by stokla** [comment]
hi meriadec,
so I did already and talk with them the whole day. but we still not at the end. it's a quite strange problem. 
the browser support I checked already when I started in the morning today. it always was off.
If I change during the connection process the settings for Browser support from NO to YES, save it and set it back to NO and save again, then my ETH account get connected. 
But that I have to do always when I do something about ETH :-( 
Maybe it's a helpful information for your Dev's. I dont think, that it is a problem of my Nano S, or? I just bought it about 2 month ago.

**Comment by meriadec** [comment]
we are the devs so yep ^^ definitely a helpful symptom to signal.

**Comment by RicoTB** [comment]
I have the same problem with app ETH.
W10 ledger nano S

**Comment by gre** [comment]
Wait our next 1.0.2 and it should be fixed 🤞

**Comment by RicoTB** [comment]
Oh super, merci

Le jeu. 12 juil. 2018 13:46, Gaëtan Renaudeau <notifications@github.com> a
écrit :

**Pull request merged**
