### PR TITLE
Swap drop the landing screen for spectron

### PR DESCRIPTION
**Pull request by juan-cortes**
With the merger of the swap Wyre, we broke (even more) the swap Spectron test. I'm not going to uncomment the commented tests because we are moving away from this flow completely and it should be part of that pr.

### Type

QA

### CODE REVIEW

**Comment by juan-cortes** [comment]
This will not work 🤔

**Review by gre — CHANGES_REQUESTED** [review]
still not passing?

**Comment by juan-cortes** [comment]
Nope, doesn't seem to want to pass

**Comment by juan-cortes** [comment]
Spectron, We haven't touched ETH at all, why are you doing this to me

**Comment by juan-cortes** [comment]
Closes https://github.com/LedgerHQ/ledger-live-desktop/pull/4066 since it includes the https://github.com/LedgerHQ/ledger-live-desktop/pull/4067/commits/db34128823d127990cced5e5a714324ba3ba982f commit from @LFBarreto

**Review by gre — APPROVED** [review]

**Pull request merged**
