### PR TITLE
Release/2.41.x

### PR DESCRIPTION
**Pull request by lambertkevin**

### CODE REVIEW

**Comment by lambertkevin** [comment]
# Changelog

LLD 2.41.0

## 🚀 Features:
- Market: Update logic to limit refreshes in Market page #4861 @LFBarreto 
- Legacy: Sunset Libcore 👋 #4867 @greweb @haammar-ledger
- NFT: New architecture and support for Polygon #4870 @lambertkevin
- NFT: New filtering system #4868 @grsoares21 
- NFT: Improve support for collection names #4899 @lambertkevin
- Networks: Add support for Goerli #4876 @hzheng-ledger
- Solana: Add support for staking #4884 @haammar-ledger


## 🐛 Bufixes:
- NFT: Fix missing collection names in summary #4898 @lambertkevin


## ⚠️ Dependabots:
- #4866
- #4890
- #4891

**Review by ghost — APPROVED** [review]

**Comment by lambertkevin** [comment]
# Changelog

LLD 2.41.1

## 🐛 Bufixes:
- Solana: Fix validator list not showing up https://github.com/LedgerHQ/ledger-live-common/pull/1902 #4938 @haammar-ledger @henrily-ledger

**Comment by lambertkevin** [comment]
# Changelog
v2.41.2

## 🐛 Bugfixes:
- NFT: Fix breadcrumb not working anymore (wrong selection and no action on click) @lambertkevin #4950
- NFT: Fix app crash when sending the last NFT owned in a collection @lambertkevin #4953

## 🧱 Support:
- Legacy: Removing (again) libcore dependency @haammar-ledger #4951 

## 🔗 Dependencies:
- Update @ledgerhq libs to the latest versions @lambertkevin https://github.com/LedgerHQ/ledger-live-desktop/pull/4894/commits/81782e4f3638686b96dd2f4a2beb7ee0dad79030
- Upgrade to LLC to v22.0.3

**Comment by lambertkevin** [comment]
# Changelog 
v2.41.3

## 🐛 Bugfix: 
- NFT: Fix NFT crumb dropdown causing a crash after send @lambertkevin #4958

**Pull request merged**
