### PR TITLE
adds error modal if getLatestFirmwareForDevice fails

### PR DESCRIPTION
**Pull request by valpinkman**
If `getLatestFirmwareForDevice` fails, display a modal with Error

### Type

Improvement

### Context

LL-1245

### Parts of the app affected / Test plan

Manager / Firmware Update

image

### CODE REVIEW

**Comment by gre** [comment]
what I was suggesting in LL-1245 (comment) is that we should be erroring in the error case of the Firmware modal. because we're in the context of a firmware update.

we don't need to introduce a new modal but just reuse the existing modal. is it feasible?

**Comment by valpinkman** [comment]
Reusing update firmware modal

image

**Comment by gre** [comment]
neeeaaaat!

**Comment by gre** [comment]
@Arnaud97234 i would suggest we merge it because we'll have more to test regarding firmware update in my other live-common PR. i would like to rebase it with it. is that ok we merge it and test again later?

**Pull request merged**
