### PR TITLE
Bash scripts refactoring

### PR DESCRIPTION
**Pull request by meriadec**
No real feature involved, just internal bash scripts refactoring.

It will ease development onboarding/debugging, by clearly displaying environment and visually separate jobs steps. Also, cache checking for flow-typed and native modules has been improved/fixed.

Existing scripts has been moved to `scripts/legacy` so no worry they will continue to work until we have time to refacto.

List of commands that have been refactored:
- `postinstall.sh`
- `yarn start`
- `yarn release`
- `yarn dist`
- `yarn dist:dir`
- `yarn compile`

Big picture is to prepare publishing via CI directly. The few helpers inside the PR will be handy.

### General commands are displaying env
yarn

### Example of a success job
compile

### Example of a failing job
compile-fail

### CODE REVIEW

**Comment by meriadec** [comment]
⚠️ **DONT MERGE**

as usual, Windows is blocking. Git bash impl is not providing stdin...

```
scripts/helpers/run-job.sh: line 15: /dev/stdin: No such file or directory
```

**Comment by gre** [comment]
i wouldn't merge this before next week , let's focus on 1.0.2 first and probably see it.

**Comment by meriadec** [comment]
totally why we have that hodl badge :)

**Comment by gre** [comment]
🚀

**Pull request merged**
