### PR TITLE
Show time inside the tooltip on account charts when week range is selected

### PR DESCRIPTION
**Pull request by JunichiSugiura**
Time was missing in the tooltip just on Account page so I added.

### Type
Bug Fix

### Parts of the app affected / Test plan
Account page -> hover on the chart to see tooltip. It should be the same to the one on Portfolio.

### CODE REVIEW

**Review by gre — APPROVED** [review]

**Review by nabil-brn — CHANGES_REQUESTED** [review]
It's back 👍 but why `range === "week" ?`, it's not the case on portfolio, the time is on all charts.
cc @cthepot-ledger

---
Windows
4533c7e5b (grafted, HEAD -> hotfix/account-chart, ledger/hotfix/account-chart) show time on account charts

**Comment by gre** [comment]
@JunichiSugiura we should prefer ask live-common the granularity, because in future we'll add more like 1D
https://github.com/LedgerHQ/ledger-live-common/blob/master/src/portfolio/range.js#L46

**Comment by JunichiSugiura** [comment]
It should always show time no mater what granularity/range is selected now. Although it no longer necessary, I'll keep in mind about `granularityId` property for feature tasks.

**Review by gre — APPROVED** [review]

**Review by nabil-brn — APPROVED** [review]
The time is back on all charts in account section.

---
Windows
157de039 (HEAD -> hotfix/account-chart, ledger/hotfix/account-chart) display time no matter what granualarity/range is selected

**Pull request merged**
