### PR TITLE
LL-2885 Update link/wording for lostSeed link

### PR DESCRIPTION
**Pull request by juan-cortes**
### Type

Wording

### Context

https://ledgerhq.atlassian.net/browse/LL-2885

### Parts of the app affected / Test plan

Trigger a firmware update and check the wording and link are correct, although I don't see how this one could go wrong.

### CODE REVIEW

**Comment by juan-cortes** [comment]
No qa was assigned to this

**Comment by gre** [comment]
@juan-cortes can you attach the new screenshot so it pass CI?

**Comment by juan-cortes** [comment]
@nabil-brn you are 100% correct, I took it as simply changing the wording and not as making it dynamic as clearly stated in the jira task. I'll address, good QA :beau:

**Comment by juan-cortes** [comment]
@nabil-brn @gre Updated making the URL dynamic depending on the device model. For the Blue, there doesn't seem to be any specific URL for the lost-seed case so I'm just linking to the manual. If you have a better suggestion please update the URL directly with a suggested edit, that would be the quickest (and avoid me having to jump back into this branch), thank you!

**Comment by dasilvarosa** [comment]
> For the Blue, there doesn't seem to be any specific URL for the lost-seed case so I'm just linking to the manual. If you have a better suggestion please update the URL directly with a suggested edit

Please maintain the Ledger Nano S article for the Blue. That's more relevant than the Blue manual.

**Comment by juan-cortes** [comment]
> Could we fix the cursor on hover?
> Comment from @dasilvarosa
> 
> > The link in the release notes (blog post) does not change the cursor in hover state to show that it is clickable

To me it's a totally unrelated issue, this is for the firmware update lost seed link, then again, I went to check it and indeed we don't put the pointer cursor, I've changed it, please check @Arnaud97234 

image

**Comment by juan-cortes** [comment]
> > For the Blue, there doesn't seem to be any specific URL for the lost-seed case so I'm just linking to the manual. If you have a better suggestion please update the URL directly with a suggested edit
> 
> Please maintain the Ledger Nano S article for the Blue. That's more relevant than the Blue manual.

Sure, done

**Pull request merged**
