### PR TITLE
bump electron to 11.1

### PR DESCRIPTION
**Pull request by valpinkman**
Update our electron dependencies to the latest versions and some other libraries.

### Type

Dependencies upgrade

### Context

LL-4195

### Parts of the app affected / Test plan

 - Overhaul of the whole app
 - Testing libcore coins (bitcoin families)
 - System features (reset / empty cache etc...)
- includes https://github.com/LedgerHQ/ledger-live-common/releases/tag/v17.6.0
- includes https://github.com/LedgerHQ/ledger-live-common/releases/tag/v17.6.1
- includes https://github.com/LedgerHQ/ledger-live-common/releases/tag/v17.7.0
- fixes https://ledgerhq.atlassian.net/browse/LL-4034
- fixes https://ledgerhq.atlassian.net/browse/LL-2943
- OperationDetail countervalues is using the operation date

### CODE REVIEW

**Review by gre — APPROVED** [review]
wow

**Comment by gre** [comment]
(mmh check CI)

**Comment by gre** [comment]
@valpinkman can you try to get in sync with develop? Test should pass

**Comment by gre** [comment]
@valpinkman can you try to revive this PR and try to make it pass CI?

**Review by gre — APPROVED** [review]

**Review by nabil-brn — APPROVED** [review]

**Review by gre — APPROVED** [review]

**Pull request merged**
