### PR TITLE
Fixes windows virus false-positive issue due to electron-builder

### PR DESCRIPTION
**Pull request by gre**
Revert to older electron-builder because of https://github.com/electron-userland/electron-builder/issues/4793

### Type

bug fix

### Context

- https://github.com/electron-userland/electron-builder/issues/4793
- we might want to reborn in future the work of https://github.com/LedgerHQ/ledger-live-desktop/pull/2815

### Parts of the app affected / Test plan

- this PR affects electron so we should check the overall app is fine.
- Check that builds on Linux / Mac / Windows are fine => which is essentially covered by the CI already!

### CODE REVIEW

**Comment by gre** [comment]
it works

**Comment by asohbat** [comment]
2.2.3 win
Untitled

**Comment by asohbat** [comment]
> it works

it does not . 2.2.3 windows
Untitled

**Comment by tomasz-s** [comment]
Just installed 2.2.3. Same problem. 
And, its new. I've never had this problem before.

**Pull request merged**
