### PR TITLE
LL-5194 - fix(MainSideBar): disable Lend and Buy&Sell buttons if no accounts

### PR DESCRIPTION
**Pull request by ghost**
### Type

UI Bug Fix

### Context

When starting a fresh app with no accounts, Lend and Buy / Sell buttons are not disabled.
This PR disabled Lend and Exchange when user have no account.

### Parts of the app affected / Test plan

The main side bar.
image

### CODE REVIEW

**Review by machard — DISMISSED** [review]

**Review by juan-cortes — DISMISSED** [review]

**Review by gre — APPROVED** [review]

**Review by gre — CHANGES_REQUESTED** [review]
@rjarasson-ledger please regenerate screenshots.

**Comment by rjarasson-ledger** [comment]
YAY it's passing.

@gre btw, i don't know if you expect us to regenerate screenshots locally, but last time i tried (before the engine / workflow change), it was running indefinitely on my mac.

FYI, So screenshots were not updated because i was waiting for the ci to passe and produce the zip of screenshots to be updated (and github to provide good tool for seeing changes easily).

I pushed force my rebase so review was discarded, but no code change made.

**Comment by juan-cortes** [comment]
> YAY it's passing.
> 
> @gre btw, i don't know if you expect us to regenerate screenshots locally, but last time i tried (before the engine / workflow change), it was running indefinitely on my mac.
> 
> FYI, screenshots were not updated because i was waiting for the ci to pass and produce the zip of screenshots to be updated (and github to provide good tool for seeing changes easily).
> 
> I pushed force my rebase so review was discarded, but no code change made.

We no longer generate the screenshots locally, you download the generated ones from CI and commit the changed screenshots

**Review by juan-cortes — DISMISSED** [review]

**Comment by gre** [comment]
yeah it's not exactly matching as it depends on the machine that screenshot unfortunately. however I would like to be able to ping the bot to commit in a PR in future if we can make it possible for convenience.

**Review by gre — DISMISSED** [review]

**Review by Arnaud97234 — APPROVED** [review]
Lend and Buy/Sell CTA are disabled for LL empty state. GO

**Pull request merged**
