### PR TITLE
fixed string templates to show amounts again when having german display language

### LINKED ISSUE #4463: TRX reward claims not shown with german display language
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.35.2
- Platform and version: Windows 10 Pro

#### Expected behavior

When having german display language, the claim for TRX button should show the amount.

#### Actual behavior

When having german display language, the claim for TRX button does NOT show the amount.

#### Steps to reproduce the behavior

1. have some TRX
2. have german display language
3. have some claim for TRX

english display language:
grafik

german display language:
grafik

### PR DESCRIPTION
**Pull request by FibreFoX**
## 🦒 Context (issues, jira)

This should fix https://github.com/LedgerHQ/ledger-live-desktop/issues/4463 (and for ALGORAND too)

## 💻  Description / Demo (image or video)

Current translation contained some string template being translated too instead of staying "in english". This PR fixes by changing string templates to correct english versions to show amounts again.

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [x] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

### CODE REVIEW

**Comment by FibreFoX** [comment]
Anything that is blocking this PR getting checked/merged?

**Comment by FibreFoX** [comment]
I rebased my changes to the current `develop`-branch. Hopefully this can be merged more easy now.

**Comment by ofreyssinet-ledger** [comment]
Hello @FibreFoX, thanks a lot for noticing this issue and proposing a fix 🙏
We can't actually push a fix on languages other than english directly in the code as the source of truth for these is an external tool we are using (we download translation files from that tool) and the next update of the translation files would override any change made. However our translation team has fixed the issue and the fix should be available in the next release. Thanks again!

**Comment by FibreFoX** [comment]
Hi @ofreyssinet-ledger, thanks for the feedback. I figured that you are using some external database/tool for managing translations. but I was unable to find any way to contribute to that. Maybe you want to add some note about that to the README file or so ;) glad that I could help

**Pull request closed without merging**
