### PR TITLE
Fix app actions overflow

### PR DESCRIPTION
**Pull request by nparigi-ledger**
## 🦒 Context (issues, jira)

image

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

### CODE REVIEW

**Review by LFBarreto — DISMISSED** [review]
:rocket: 
@nparigi-ledger need to fix conflicts and go merge

**Comment by nabil-brn** [comment]
Come on CI! 😢  EC2 refused to boot up.

**Comment by nabil-brn** [comment]
✅  QA-ed

Bug still occurs on a different language, related issue has been created, I'm ok to merge this as a workaround for english language.
---
f3a03d55e (HEAD -> LL-8794-fix-app-actions-overlap, ledger/LL-8794-fix-app-actions-overlap) Merge branch 'develop' into LL-8794-fix-app-actions-overlap

**Review by nabil-brn — APPROVED** [review]
Screenshots ✅ 
CI is happy ❤️

**Pull request merged**
