### PR TITLE
CI - use vercel to cancel previous flows

### PR DESCRIPTION
**Pull request by machard**

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]

**Comment by machard** [comment]
actually i think that instead of canceling previous flow, we should just avoid posting a comment if a new run has been started AFTER.
===> we get the check/crosses on intermediate commit AND only the last comment

**Comment by valpinkman** [comment]
I think a rebase is needed

**Comment by machard** [comment]
looks like starting today the pull_request token has permission to cancel previous workflow :/

**Comment by valpinkman** [comment]
as seen with @machard, we have transfered the repo to ledgerhq, awaiting validation to integrate it in Vercel.

when it's done, we'll need to update the url to reflect the change.

**Review by valpinkman — CHANGES_REQUESTED** [review]
update url when ready

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
