### PR TITLE
Update live-common and libcore to benefit recent fixes

### PR DESCRIPTION
**Pull request by gre**
- Tezos fixes (HTTP 400 for some accounts. KT accounts issue with more than 100 ops)
- ~new Tezos legacy derivation path (44'/1729'/0'/0'/<account>' and 44'/1729'/0'/<account>')~ This is skipped because problem along this found by @Arnaud97234 . we'll attempt https://github.com/LedgerHQ/ledger-live-common/pull/457 but not in this hotfix PR
- ERC 20 new update

### CODE REVIEW

**Comment by guycaprio** [comment]
Ledger Live 1.20.0-nightly.20191226T2136

- [x] Send / Sync [BTC](https://blockstream.info/tx/f30ba121bcb44a0a2d094ceafbe8b9a8e9d0d06e36850131ad784770e4ddacb5)
- [x] Send / Sync [ETH](https://etherscan.io/tx/0xaffe60c0ef2062936594117d7be62e1ba9adf845192a5bdd441504459e2a034c)
- [x] Send / Sync [ZRX](https://etherscan.io/tx/0x1d04ade973302dff71e49faf99c8e5cb9d69509d651d374d95eda258e3575aba) (ETH ERC20)
- [x] Send / Sync [ETC](https://receipt.emeraldpay.io/tx/0x0834e0eb93c408360eaf85c25468668fc25ee87fe0a6a679518c4c46d4af8edf)
- [x] Send / Sync [XRP](https://bithomp.com/explorer/919F301ECD151B781FDB075CD2946C3EAAF2963EC55C0C6F9F870090E6C1101B)
- [x] Send / Sync [XTZ](https://tzstats.com/oni97UrQyN6jbQgrKNgd8CAupwGcMAnRQ2uRJNLcLGenK4pQoGK)
- [ ] Send / Sync ZEC
- [ ] Send / Sync KMD
- [ ] Send / Sync ZEN
- [ ] Send / Sync XST
- [ ] Send / Sync DCR

**Comment by gre** [comment]
@guycaprio the PR was updated with latest fixes (erc20 and bakers list updated, but also, if the KT disappearance was affected in this PR, it should be fixed (but I don't think it was affected here))

**Comment by guycaprio** [comment]
List of tested transactions:

MacOS:
**✓** Send / Sync [XTZ](https://tzstats.com/opQXZQncdupXTnJiTj83TfTFQ2NrjiESSJNee5r8BkCdKoc5zKE)
**✓** Send / Sync [ZEC](https://sochain.com/tx/ZEC/2d3891f085f1e1d83133df4ed912fa180464497958672d66f0f436cfeda4abaf)
**✓** Send / Sync [KMD](https://kmdexplorer.io/tx/c003dbce810ee54a91b46d8cc48ee6c7e3184235d48e9160fdc082cec990c517)
**✓** Send / Sync [ZEN](https://explorer.zensystem.io/tx/e3b7e9409f7ef40d43850d425e35eb158617d326247a5bfb54c1d28e661f431c)
**✓** Send / Sync [XST](https://chain.stealth.org/tx/e14271846e1bc77bf880360d97d2ff6a36a87f1d71a7589e64748babf03efcbb)
**✓** Send / Sync [DCR](https://mainnet.decred.org/tx/8622555253793cdfb69266c5ec0095b626235afbb92a939d40863be6b814d9fa)

Linux:
**✗** Sync XTZ
tezos_add_accounts

Windows (not tested):
... Send / Sync BTC
... Send / Sync ETH
... Send / Sync ZRX 
... Send / Sync ETC
... Send / Sync XRP

---
fb14a7ee (HEAD -> bump-live-common-9-patch, gre/bump-live-common-9-patch) Update live-common@9.3.4

**Comment by guycaprio** [comment]
Thanks to @Arnaud97234, I could test _Tezos fixes (HTTP 400 for some accounts. KT accounts issue with more than 100 ops)_

Capture d’écran 2020-01-29 à 15 24 43

**✓** No HTTP error, KT accounts retrieved successfully

**Comment by gre** [comment]
so my understanding is we are good on Mac (Windows too?) but we have a crash on Linux?

**Comment by gre** [comment]
Due to complications with Linux build and disruption of Node8 support, we've decided to cancel this patch release in order to focus on our "bigger rework" that shall soon come back to this repository.

**Pull request closed without merging**
