### PR TITLE
LL-6072 [Polkadot] Adapt UI to dynamic minimum bond value

### PR DESCRIPTION
**Pull request by ghost**
https://ledgerhq.atlassian.net/browse/LL-6072
https://ledgerhq.atlassian.net/browse/LL-6162
https://ledgerhq.atlassian.net/browse/LL-6164

:warning: Requires live-common PRs fist:
- https://github.com/LedgerHQ/ledger-live-common/pull/1280
- https://github.com/LedgerHQ/ledger-live-common/pull/1307

### Type

Feature

### Context

In order to nominate Polkadot requires a minimum bonded balance. They like to change its value pretty often. So on our side, instead of having it hardcoded (currently at 1 DOT) we now fetch the current value from the network.

Note: current minimum bonded balance as of 1st July 2021 is **40 DOT** .

### Parts of the app affected / Test plan

This PR has 2 changes:
- When trying to `bond` or `bond_extra`, the error message now uses the current minimum bond value of the network.
image

- When the account has currently less than the minimum bond value, a warning is displayed on both the bonded balance and the Nominate modal:
polkadot-min-bond-warning
image

### CODE REVIEW

**Review by IAmMorrow — DISMISSED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
When accessing to a Polkadot account LLD crash with the following:
```
Object(...) is not a function
TypeError: Object(...) is not a function
    at AccountBalanceSummaryFooter (webpack-internal:///./src/renderer/families/polkadot/AccountBalanceSummaryFooter.js:24:25669)
    at renderWithHooks (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14986:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17812:13)
    at beginWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19050:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3995:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:4057:31)
    at beginWork$1 (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23960:7)
    at performUnitOfWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22772:12)
    at workLoopSync (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22703:5)
```
[ledgerlive-logs-2021.07.09-16.31.54-93bdf372e.json.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/6792144/ledgerlive-logs-2021.07.09-16.31.54-93bdf372e.json.txt)

**Comment by haammar-ledger** [comment]
> When accessing to a Polkadot account LLD crash with the following:
> 
> ```
> Object(...) is not a function
> TypeError: Object(...) is not a function
>     at AccountBalanceSummaryFooter (webpack-internal:///./src/renderer/families/polkadot/AccountBalanceSummaryFooter.js:24:25669)
>     at renderWithHooks (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14986:18)
>     at mountIndeterminateComponent (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17812:13)
>     at beginWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19050:16)
>     at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3946:14)
>     at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3995:16)
>     at invokeGuardedCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:4057:31)
>     at beginWork$1 (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23960:7)
>     at performUnitOfWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22772:12)
>     at workLoopSync (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22703:5)
> ```
> 
> [ledgerlive-logs-2021.07.09-16.31.54-93bdf372e.json.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/6792144/ledgerlive-logs-2021.07.09-16.31.54-93bdf372e.json.txt)

As discussed, probably due to LLC being merged but not yet bumped in LLD & LLM.
Please try using `yalc`.

**Comment by Arnaud97234** [comment]
@haammar-ledger I have a duplicate error when launching LLD:
```
duplicated @ledgerhq/hw-transport library
Error: duplicated @ledgerhq/hw-transport library
    at check (webpack-internal:///./node_modules/@ledgerhq/live-common/lib/sanityChecks.js:38:13)
    at checkLibs (webpack-internal:///./node_modules/@ledgerhq/live-common/lib/sanityChecks.js:23:3)
    at init (webpack-internal:///./src/renderer/init.js:43:30894)
    at Module.eval (webpack-internal:///./src/renderer/init.js:43:39232)
    at eval (webpack-internal:///./src/renderer/init.js:46:30)
    at Module../src/renderer/init.js (http://localhost:8080/webpack/renderer.bundle.js:67187:1)
    at __webpack_require__ (http://localhost:8080/webpack/renderer.bundle.js:790:30)
    at fn (http://localhost:8080/webpack/renderer.bundle.js:101:20)
    at eval (webpack-internal:///./src/renderer/index.js:3:72)
    at Module../src/renderer/index.js (http://localhost:8080/webpack/renderer.bundle.js:67175:1)
```

**Comment by haammar-ledger** [comment]
> @haammar-ledger I have a duplicate error when launching LLD (I did yalc add @ledgerhq/live-common) :
> 
> ```
> duplicated @ledgerhq/hw-transport library
> Error: duplicated @ledgerhq/hw-transport library
>     at check (webpack-internal:///./node_modules/@ledgerhq/live-common/lib/sanityChecks.js:38:13)
>     at checkLibs (webpack-internal:///./node_modules/@ledgerhq/live-common/lib/sanityChecks.js:23:3)
>     at init (webpack-internal:///./src/renderer/init.js:43:30894)
>     at Module.eval (webpack-internal:///./src/renderer/init.js:43:39232)
>     at eval (webpack-internal:///./src/renderer/init.js:46:30)
>     at Module../src/renderer/init.js (http://localhost:8080/webpack/renderer.bundle.js:67187:1)
>     at __webpack_require__ (http://localhost:8080/webpack/renderer.bundle.js:790:30)
>     at fn (http://localhost:8080/webpack/renderer.bundle.js:101:20)
>     at eval (webpack-internal:///./src/renderer/index.js:3:72)
>     at Module../src/renderer/index.js (http://localhost:8080/webpack/renderer.bundle.js:67175:1)
> ```

@Arnaud97234 Sorry about that, but it seems that LLC master is not aligned with LLD develop.
Nothing I can do about it, but you can workaround the issue by doing:

`yarn install && yarn-deduplicate && yarn install`

(doing `yarn install` twice is important)

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
Bug found: https://ledgerhq.atlassian.net/browse/LL-6408
UX improvement (need to be confirmed by product / design): https://ledgerhq.atlassian.net/browse/LL-6406

**Review by Arnaud97234 — APPROVED** [review]
The behavior is OK, I think in the future we could just improve the warning / Error message for "You must bond at least ... DOT to be able to Nominate and generate rewards"

**Comment by haammar-ledger** [comment]
> The behavior is OK, I think in the future we could just improve the warning / Error message for "You must bond at least ... DOT to be able to Nominate and generate rewards"

I agree with the idea, the issue is that we need to keep validation messages short so they fit in the modals.

**Pull request merged**
