### PR TITLE
Correctly handle sequence when UTXO script length is 0

### PR DESCRIPTION
**Pull request by meriadec**
TL;DR, following #1386, we identified & reproduced `0x6f01` error, occurring in the specific case of having a 0 length script in inputs, which resulted in not passing sequence in the transaction. So the fix is located in [ledgerjs/hw-app-btc](https://github.com/LedgerHQ/ledgerjs/commit/2b3ed5a60b4e4b42613d7c773a67fb7d42c22e12).

Thanks @btchip, @pollastri-pierre and @KhalilBellakrid for helping on this one! :rocket:

### CODE REVIEW

**Comment by gre** [comment]
needs important QA testing on if everything still work fine. also would deserve to **build** the app and test a build , to double check babel change things.

**Comment by meriadec** [comment]
+1 for the test plan (and it will be tricky to test: I don't reproduce anymore since my UTXOs now not anymore contains empty scripts. I guess we will need faucets random luck.

@Arnaud97234 don't hesitate if you need my help

**Comment by gre** [comment]
i mean. the utxo fix is just bumping some libs. i was more talking about the rest of this PR :p

**Comment by meriadec** [comment]
I splitted into another PR https://github.com/LedgerHQ/ledger-live-desktop/pull/1573 so it's more atomic

**Comment by Arnaud97234** [comment]
Tested with Bitcoin Testnet and didn't get the error.
No regression found (Currencies used BTC, LTC, DGB, BCH, ETH, XRP).

**Pull request merged**
