### PR TITLE
LL-5438 - Fix select use case onboarding link

### PR DESCRIPTION
**Pull request by machard**
https://ledgerhq.atlassian.net/browse/LL-5438

### CODE REVIEW

**Review by LFBarreto — CHANGES_REQUESTED** [review]
I dont think thats what needs to be done. The learn more actually opens a drawer where you should find a link, update it here
https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/renderer/components/Onboarding/Help/RecoveryWarning.js#L22

**Review by juan-cortes — DISMISSED** [review]
If that's the right url, lgtm

**Review by LFBarreto — DISMISSED** [review]

**Review by stual-ledger — CHANGES_REQUESTED** [review]
Unfortunately, clicking this link still brings up a drawer on the side instead of the expected url (see screenshots below)

Reference # for the commit it was tested on : `6a784b4e982a2cfd1fd06c90e0b05ea3bde4fd1b`

Screenshot 2021-08-09 at 15 57 03

**Review by valpinkman — APPROVED** [review]

**Review by ychen-ledger — APPROVED** [review]
Validated with:

- MacOs big Sur 11.4
- Nano X / Nano S

**Pull request merged**
