### PR TITLE
Ll 8456 add send buttons nfts + live-common bump

### PR DESCRIPTION
**Pull request by gre**
## 🦒 Context (issues, jira)

- LL-8456 add send buttons nfts – making it consistent with LLM
- fixes of https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.19.1

### CODE REVIEW

**Comment by gre** [comment]
@klambert-ledger please mention all the LL- ticket of your fixes here

**Comment by gre** [comment]
we have to fix some bugs before reopening

**Review by imqdee — APPROVED** [review]
LGTM

**Pull request merged**
