### PR TITLE
Put back the original architecture image for now

### PR DESCRIPTION
**Pull request by meriadec**
Let's keep the old architecture image, because its purpose is to rapidly explain the architecture, and despite the fact that this one is less pretty, it's more explainful, and that's its job

### CODE REVIEW

**Comment by gre** [comment]
please rollback in the readme too. we'll merge for now

**Comment by gre** [comment]
unless we have a better schema in time

**Comment by meriadec** [comment]
it's the same img name

**Comment by gre** [comment]
AH yes

**Pull request merged**
