### PR TITLE
Merged language files into a single file for easier translation

### PR DESCRIPTION
**Pull request by valpinkman**

### CODE REVIEW

**Comment by gre** [comment]
Is there a way we can remove the need to do app: ? I think we can tell the i18n lib the default

**Comment by juan-cortes** [comment]
I don't have permissions to this for you guys (since I'm just the random dev from spain) but it's a matter of adding `defaultNS: 'app',` to [renderer/i18n/instanciate.js#L5](https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/renderer/i18n/instanciate.js#L5), this changes the default from `'translation'` to `'app'`. Allowing us to remove all the `app:` prefixes.

**Comment by valpinkman** [comment]
@juan-cortes thanks, done

**Comment by gre** [comment]
@Arnaud97234 could you check all texts are fine on the current develop app? normally it's all good but we never know 👍

**Comment by gre** [comment]
just checking there is nowhere text like `app.foo.bar` ^^

**Comment by Arnaud97234** [comment]
@gre, I've made checks on all screen of the app. Everything seems correct.

**Comment by gre** [comment]
thanks!!!

**Pull request merged**
