### PR TITLE
LIVE-1569 Add "Hide NFT Collection" feature

### PR DESCRIPTION
**Pull request by grsoares21**
## 🦒 Context (issues, jira)
This feature allows the user to hide NFT collections. The hidden NFT collections are saved as part of the user's settings and can be unhidden in the settings page under the "Accounts" tab.
[LIVE-1569]

## 💻  Description / Demo (image or video)
nft-hide-collection

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

[LIVE-1569]: https://ledgerhq.atlassian.net/browse/LIVE-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by tlaforge-ledger — APPROVED** [review]
That's a good one !

**Review by juan-cortes — APPROVED** [review]
Make sure all the screenshots make sense, the last two seem glitchy ?

**Comment by grsoares21** [comment]
> 

Indeed, the last 3 even don't seem related with this PR. But they all have the same exact diff (the exchange screen is a bit scrolled down compared to before), I wonder if anything changed on the playwright tests for that.

**Comment by grsoares21** [comment]
Reverted the glitchy screenshots. If this keeps happening on other PRs we should check what changed and why the screenshots weren't updated before.

**Review by ghost — APPROVED** [review]

**Pull request merged**
