### PR TITLE
[LL-3809] add tooltip to transaction device fields

### PR DESCRIPTION
**Pull request by henri-ly**
### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-3809

### Parts of the app affected / Test plan

Lend for withdraw asset,  I wasn't able to test it because eth fees cost too much :/ 

We should also wait for a bump of LLC : https://github.com/LedgerHQ/ledger-live-common/pull/1115

### CODE REVIEW

**Review by LFBarreto — DISMISSED** [review]

**Review by LFBarreto — APPROVED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
###Bug found
@henri-ly 
In the tooltip the text say "cDAI" even for other currencies. In my example I'm using USDT but the tooltip talk about DAI.
Also a blank space is missing "...cDAI.cDAI..." should be "...cDAI. cDAI..."

image

**Review by Arnaud97234 — COMMENTED** [review]
@henri-ly {{ tokenName }} value is missing in the tooltip.
image

**Comment by henri-ly** [comment]
Weird, maybe the live-common wasn't update, I rebase, can you check that live-common version is at least 19.4.0 ?

**Comment by LFBarreto** [comment]
closing this one for #3779

**Pull request closed without merging**
