### PR TITLE
LL-1106 Export operations

### PR DESCRIPTION
**Pull request by juan-cortes**
Adds the ability to export operations for users, for now, we don't have the time period selection and it will export the whole thing. ~We are missing the success text still, @dasilvarosa when you come up with a copy for it I'll integrate it!~

Group

### CODE REVIEW

**Comment by juan-cortes** [comment]
image

Ready for retesting after design changes @valpinkman @Arnaud97234

**Comment by juan-cortes** [comment]
@gre live-common impl?

**Comment by gre** [comment]
we need to see if `\r\n` can help here

**Comment by gre** [comment]
@juan-cortes  if you merge develop in, you might have the fix for \r\n

**Comment by juan-cortes** [comment]
It had an unnecesary json stringify, it worked with the old version

**Pull request merged**
