### PR TITLE
eip55 validation for ethereum recipient addresses

### PR DESCRIPTION
**Pull request by MortalKastor**
### Type

Bug Fix for ETH recipient addresses not being correctly validated

### Parts of the app affected / Test plan

Send flow

### CODE REVIEW

**Comment by gre** [comment]
Are we ok doing and have we studied the general support of that  e.g. among exchanges / other wallets / eth community? the risk is that potentially people will be stuck trying to send funds to address that is not eip formatted.
To mitigate the problem you could ignore (aka keep doing basic validation like before) if and only if there are either ONLY lower case or ONLY upper case.

**Comment by gre** [comment]
https://www.reddit.com/r/ledgerwallet/comments/95hqh5/trying_to_exchange_ethereum_classic_on_shapeshift/?utm_source=reddit-android

**Comment by gre** [comment]
I've checked and for instance Wirex give a lower case address so I would recommend testing this (does eip55 lib support this case, I see it's only suggested in the spec GitHub comments) or implement the ignore "all lower or all upper"

**Comment by meriadec** [comment]
What about having an additional warning box or a "I confirm this address is valid" cta if we can't pass the eip55 check (if mixed lower/upper)? Can be useful to inform user of eventual typo (bad copy paste/bad qr code scan)

**Comment by meriadec** [comment]
follow up https://github.com/LedgerHQ/ledger-live-desktop/pull/1400

**Pull request merged**
