### PR TITLE
LIVE-1351 Replace onboarding illustrations with the new logo

### PR DESCRIPTION
**Pull request by juan-cortes**
## 🦒 Context (issues, jira)
https://ledgerhq.atlassian.net/browse/LIVE-1351

## 💻  Description / Demo (image or video)
Just updated illustrations while the rebranding is incoming to show the new logo instead of the old one. Bunch of updated screenshtots I would assume.

Screenshot 2022-02-17 at 11 03 30
Screenshot 2022-02-17 at 11 03 26
Screenshot 2022-02-17 at 11 03 17
Screenshot 2022-02-17 at 11 02 57

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

### CODE REVIEW

**Comment by blucet-ledger** [comment]
That's a nice win, thanks @juan-cortes!

**Review by thomasrogerlux — APPROVED** [review]

**Pull request merged**
