### PR TITLE
Validators toggle assets display

### PR DESCRIPTION
**Pull request by henri-ly**
### Type

Bug-fix:  
the offset was off when we :
      - do a first search with few results and scroll on the bottom of it
      - then do one more search but with no result
        and redo a research with a result, no items will be display in the scrollContainer

Features : 
- @rjarasson-ledger add a `/maxVotes` to the number of selected voted
- For Polkadot Purpose we do not need the display of "All assets are distributed" because to delegate to a validator in this blockchain you only need to add the address, the blockchain will automatically distributed your locked assets.

### Parts of the app affected / Test plan

Validators list

### CODE REVIEW

**Comment by gre** [comment]
Which currency are currently using this ?
It would help QA to know what to test.

Thanks

**Comment by henri-ly** [comment]
Tron / Cosmos is affected by the change

**Comment by rjarasson-ledger** [comment]
Adding total was a suggestion we had during Polkadot integration, but was not really planned or reviewed by a designer.
I thought it was a good idea to add it for all coins using this component.

The hideVotes props will enable Polkadot to not display the "All assets are ditributed" mention that is irrelevant.

**Review by gre — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Review by Arnaud97234 — APPROVED** [review]

**Comment by rjarasson-ledger** [comment]
Wen merge ?

**Pull request merged**
