### PR TITLE
LL-5582 remove warning when switching lang on onboarding

### PR DESCRIPTION
**Pull request by valpinkman**
- [x] language switcher uses OS lang by default
- [x] remove warning when "partial" languages were selected (incoming full translation)

### Type

Polish

### Context

LL-5582

### Parts of the app affected / Test plan

Onboarding Language Switcher

### CODE REVIEW

**Review by juan-cortes — APPROVED** [review]
lgtm

**Review by JunichiSugiura — COMMENTED** [review]
LGTM

**Review by ychen-ledger — COMMENTED** [review]
Validated with:
- MacOS Big Sur version 11.4 
- Ledger Live 2.28.
- OS language: French, English, Spanish, Russian, Chinese

**Comment by nabil-brn** [comment]
✔️ Tested also on
- [x] Windows
- [x] Linux

**Pull request merged**
