### PR TITLE
Display warning instead of rejecting ETH address without checksum

### LINKED ISSUE #1397: ETH addresses without checksum should only display a warning instead of rejecting the transaction
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.4
- Platform and version: All

#### Expected behavior

When sending ETH to an address without checksum, the Live should display a warning instead of rejecting the transaction. This because the checksum has been introduced late in the coin life cycle and many addresses don't have one.

3 cases:

- address with a correct checksum: no warning
- address without checksum: warning
- address with an incorrect checksum: transaction rejected

#### Actual behavior

The transaction is rejected.

#### Steps to reproduce the behavior

Try to send ETH to an address without checksum.

### PR DESCRIPTION
**Pull request by meriadec**
Closes #1397

This commit introduce a new `warning` prop on Input component. `error`
prop will always takes precedence over it if present, btw.

We don't reject anymore recipient validity if address is either full
lowercase OR full uppercase, to support legacy formats: having a warning
will allow user to go to next step.

Obviously the fix is available for ETC as well.

Wording to be reviewed :)

eth

***edit: wording has been updated to `Auto-verification not available: carefully verify the address`***

### CODE REVIEW

**Comment by meriadec** [comment]
@khalilbenihoud there were no warning color so I took `#f57f17` (from Google Material's palette). Feel free to discuss that.

**Comment by meriadec** [comment]
squashed :ok_hand:

**Comment by gre** [comment]
'legacy address' wording is a bit weird. Otherwise 👌

**Comment by meriadec** [comment]
Yep, it has been updated ;)

**Pull request merged**
