### PR TITLE
LL-8955 external contributions CI

### PR DESCRIPTION
**Pull request by valpinkman**
## 🦒 Context (issues, jira)

[LL-8955]

## 💻  Description / Demo (image or video)

Allows external contribution to still run the CI

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [x] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

[LL-8955]: https://ledgerhq.atlassian.net/browse/LL-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by elbywan — DISMISSED** [review]
👌 LGTM

**Review by nabil-brn — DISMISSED** [review]

**Review by elbywan — DISMISSED** [review]

**Pull request merged**
