### PR TITLE
Add ETH goerli

### PR DESCRIPTION
**Pull request by hzheng-ledger**
https://ledgerhq.atlassian.net/browse/LIVE-1766
Screenshot 2022-03-29 at 15 22 07
Screenshot 2022-03-29 at 15 22 19

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
@hzheng-ledger 
- Need to re-generate the cryptoassets.md file by running this:
`yarn test --runTestsByPath src/generate-cryptoassets-md.test.js`
- Maybe need to update this file: https://github.com/LedgerHQ/ledger-live-desktop/blob/feat/LL-1766/tests/specs/devmode.spec.ts#L11

**Comment by hzheng-ledger** [comment]
> @hzheng-ledger
> 
> * Need to re-generate the cryptoassets.md file by running this:
>   `yarn test --runTestsByPath src/generate-cryptoassets-md.test.js`
> * Maybe need to update this file: https://github.com/LedgerHQ/ledger-live-desktop/blob/feat/LL-1766/tests/specs/devmode.spec.ts#L11

Fixed

**Review by ghost — APPROVED** [review]

**Pull request merged**
