### PR TITLE
Playwright upgrade to 1.21.1

### PR DESCRIPTION
**Pull request by mcoursier-ledger**
## 🦒 Context (issues, jira)
https://ledgerhq.atlassian.net/browse/B2CQA-80
This PR aims at upgrading playwright to latest version known ~~(1.20.2)~~ 1.21.1.
Thanks to this, we are now able to make soft assertions. (won't stop test execution but it ends in error)
These soft assertions will be especially useful in the context of screenshots.

### CODE REVIEW

**Review by thomasrogerlux — APPROVED** [review]
Noice

**Review by valpinkman — APPROVED** [review]

**Comment by nabil-brn** [comment]
I'm about to péter un câble

**Comment by nabil-brn** [comment]
Okay I thing we're good, only this flaky test is remaining, let's wait tomorow to find a solution about this annoying tooltip.

**Pull request merged**
