### PR TITLE
live-common@7 ledger-core@3

### PR DESCRIPTION
**Pull request by gre**
this PR brings lot of fixes from libcore.

- Native Segwit is fixed and is in general availability :)
- Ethereum have validation on "not enough balance"
- ERC20 have validation on "not enough balance"
- ERC20 balances are correct!
- Fixes https://github.com/LedgerHQ/ledger-live-desktop/issues/1849
- self transactions of ERC20 to make two operations
- ERC20 have validation on "not enough gas"
- block gas limit 0
- Correctly showing alert modal on fees > 10% when using send max (https://ledgerhq.atlassian.net/browse/LL-1527)
- factorize in live-common the market cap sorting logic. plz check work related to listing currencies and apps & make sure we also still display the "you successfully install apps of coin X"

### CODE REVIEW

**Comment by gre** [comment]
@Arnaud97234 can you confirm there are no regression & that the PR fixes the things mentioned? thanks

**Comment by KhalilBellakrid** [comment]
For ERC20 self transactions, indeed we provide just one operation (balance will be of though since we use `balanceOf` now) but I will provide a fix for this issue !

**Comment by gre** [comment]
ETC fixed for now by not using it with libcore.

**Comment by gre** [comment]
I don't understand.

**Comment by gre** [comment]
@Arnaud97234 it should be fixed now

**Comment by gre** [comment]
oh wait i need to bump

**Comment by gre** [comment]
@Arnaud97234 if this bug is present on develop, i would assume we can still merge this PR. is it a regression?

**Comment by Arnaud97234** [comment]
@gre The ERC20 transactions are working properly on develop branch in Linux OS so yes it's a regression.

**Comment by KhalilBellakrid** [comment]
This should be fixed by : https://github.com/LedgerHQ/lib-ledger-core/commit/4e94cc1fffac52f4465e6b8ef0ad73869d5414a1

**Pull request merged**
