### PR TITLE
LL-4446 Add support for floating rates on swap

### PR DESCRIPTION
**Pull request by juan-cortes**
Includes a major live-common bump to https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.0.0

### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-4446

### Parts of the app affected / Test plan
Floating is now available in production and swap will automatically point to the v2 by default. No need for extra environment variables or changes in order to test it. Provider 1 apps, go.

- Test the full swap feature for both fixed and floating rates
- Test the new feature for flipping accounts `left <-> right` inside the swap form
- Test that the device running latest Exchange from provider 1 which shows different wording for floating and fixed rates. There's no need to complete a full swap for this particular test, you just need to reach the confirmation step and look at the device, it should display "get" vs "get estimated" or something along those lines.

### CODE REVIEW

**Comment by cthepot-ledger** [comment]
@juan-cortes not able to get the CI here

**Comment by juan-cortes** [comment]
> @juan-cortes not able to get the CI here
Older builds should have the fix for the binary payload and the rates error message as described by jl automatically since it wasn't on live side.


I'll check why it's not building artifacts

**Review by valpinkman — APPROVED** [review]

**Review by nabil-brn — APPROVED** [review]
306f29008 (HEAD -> LL-4446, juan/LL-4446) Major live-common bump

**Comment by gre** [comment]
I see a double approve, I merge.

**Pull request merged**
