### PR TITLE
Refactor some components in TypeScript

### PR DESCRIPTION
**Pull request by JunichiSugiura**

### CODE REVIEW

**Comment by gre** [comment]
i'm setting a HODL for now for QA team to focus on the bug fixes we want to get it. we'll unhodl next week.

**Comment by LukeSugiura** [comment]
"HODL for BUIDL", noted 😎

**Comment by gre** [comment]
@JunichiSugiura could you fix conflict? thanks

**Comment by JunichiSugiura** [comment]
I'll work on this tomorrow.

**Comment by JunichiSugiura** [comment]
in favor of #2912

**Pull request closed without merging**
