### PR TITLE
@ledgerhq/live-common@21.33.0

### PR DESCRIPTION
**Pull request by gre**
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.33.0

---

- LL-9216 be less strict on breaking on non user accounts
- LL-9196 Update vtc explorer url
- LL-9198 crypto-assets list update
- LIVE-1123: low amount user shouldn't be able to set everything he want
- LIVE-825 - Update market API to have an AND logic on filters instead of OR logic 
- LIVE-1186 Update Polkadot Nano app min version to v10.9160.1 
- LIVE-1338 Remove Algorand JS impl from experimental mode
- LIVE-1337 Add check for recipient not equal to sender on crypto.org 
- LIVE-886 (Market): add sparkline variation + fix issue in countervalues 

---

### CODE REVIEW

**Review by juan-cortes — APPROVED** [review]

**Comment by gre** [comment]
/generate-screenshots

mmh

**Review by ghost — APPROVED** [review]

**Comment by nabil-brn** [comment]
I don't know what happened, I just reverted a merge commit I did without signing it.

**Comment by nabil-brn** [comment]
- [ ] LL-9216 be less strict on breaking on non user accounts
- [ ] LL-9196 Update vtc explorer url
- [ ] LL-9198 crypto-assets list update
- [ ] LIVE-1123: low amount user shouldn't be able to set everything he want
- [ ] LIVE-825 - Update market API to have an AND logic on filters instead of OR logic
- [ ] LIVE-1186 Update Polkadot Nano app min version to v10.9160.1
- [ ] LIVE-1338 Remove Algorand JS impl from experimental mode
- [ ] LIVE-1337 Add check for recipient not equal to sender on crypto.org
- [ ] LIVE-886 (Market): add sparkline variation + fix issue in countervalues

---
🪟 Windows 11
596e25984 (HEAD -> live-common-21-33, origin/live-common-21-33) Merge branch 'develop' into live-common-21-33

**Comment by nabil-brn** [comment]
Github is totally drunk on this PR, don't trust the history. 🤷

**Comment by gre** [comment]
some force push broke the history and made this PR a +0 -0, so i have recreated the PR at https://github.com/LedgerHQ/ledger-live-desktop/pull/4763

**Pull request closed without merging**
