### PR TITLE
fix ctrl-r not working when app crashes

### PR DESCRIPTION
**Pull request by machard**
Fixing the fact that ctrl-r was not working when the app was crashed

### Type

Bug Fix

### Parts of the app affected / Test plan

write something wrong, see the error page, and hit ctrl-r

### CODE REVIEW

**Comment by gre** [comment]
This needs to be documented in the code.
**But this the correct behavior** to block the user to be able to Ctrl R during a critical error case. Because critical error case usually mean a crash at boot and a complete failure to set up the internal process. Ctrl R being only reloading the renderer, allowing it would permit user to bypass the problem but then experience many broken parts (literally all device actions are broken, etc. )

**Review by gre — CHANGES_REQUESTED** [review]
Check comment

**Comment by machard** [comment]
Ok. So users can refresh when not in the crash screen, and dev can do it all the time ?

**Review by gre — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Review by nabil-brn — CHANGES_REQUESTED** [review]
I'm able to [**cmd** + **R**] with a prod build (`yarn dist`) on a crash page.
Oct-30-2020 13-07-56

---
13c61762 (HEAD -> fix/ctrl-r-not-working-when-fatal-error-occured, machard/fix/ctrl-r-not-working-when-fatal-error-occured) only allow reload on crash screen if in __DEV__

**Review by nabil-brn — APPROVED** [review]
✓ QA-ed

---
fe1c7232 (HEAD -> fix/ctrl-r-not-working-when-fatal-error-occured, machard/fix/ctrl-r-not-working-when-fatal-error-occured) fix handler subscription

**Pull request merged**
