### PR TITLE
live-common 15.7.x

### PR DESCRIPTION
**Pull request by gre**
- should fixes recent TRON issues
- check that some compound / erc20 txs still works (some refinement in gasLImit calculation)
- LL-3842
- use supplyMax when creating transaction in supply
- LL-3835 added CompoundLowerAllowanceOfActiveAccountError

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
### Bug found
Just after submitting votes the the voted ongoing period should be "Just started" instead of "common.timeAgo.seconds"

IMG_1041

**Comment by Arnaud97234** [comment]
- [x] LL-3842: Already approved account should redirect to supply

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
### Bug found
- Approve an account that is already Approved and Supplied
- Enter a specific amount (disable No limit)

The following error is displayed. As explained by @LFBarreto, in that case it shouldn't be possible to approve. The error raised is not understandable by the user.

Screenshot 2020-11-05 at 21 47 39

**Comment by gre** [comment]
Luiz provided a better wording @Arnaud97234

**Review by Arnaud97234 — COMMENTED** [review]
image

OK

**Review by Arnaud97234 — APPROVED** [review]
Some fixes are remaining but they are minor, we could fix them in another PR

**Pull request merged**
