### PR TITLE
LIVE-1192 Fix app sizes in Manager

### PR DESCRIPTION
**Pull request by juan-cortes**
## 🦒 Context (issues, jira)
https://ledgerhq.atlassian.net/browse/LIVE-1192

Screenshot 2022-02-15 at 12 47 02

## 💻  Description / Demo (image or video)
The latest version of the Ledger Nano S Plus allows for block sizes that go below 1kB. For apps that are below that size product wants us to display the size in kB with one decimal point. On that line, we changed the units to be `kB` and `MB` because it seems those are the recommended units.

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [x] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

## How to test this
- Having a Ledger Nano S Plus on the latest greatest version
- Use provider 12
- Enter the manager and check that the sizes below one kB are shown as `0.X kB` and not in bytes.

### CODE REVIEW

**Review by thomasrogerlux — APPROVED** [review]
Don't have a Nano S Plus to test but code looks fine

Also today I learned kB and MB are capitalized differently

**Review by OlivierFreyssinet — APPROVED** [review]

**Comment by juan-cortes** [comment]
> Don't have a Nano S Plus to test but code looks fine
> 
> Also today I learned kB and MB are capitalized differently

Me too, but product proved it so I won't argue

**Comment by juan-cortes** [comment]
I should've argued @ofreyssinet-ledger ! We should've argued!
:trollface:

**Comment by ofreyssinet-ledger** [comment]
Yeah haha true @juan-cortes 😬

**Comment by ofreyssinet-ledger** [comment]
As you said on slack in the end what matters isn't if it's 1KB or 1kB, it's how much apps can fit on the device 🤷

**Pull request merged**
