### PR TITLE
LL-3422 (Accounts): no accounts placeholder image loaded as react component

### PR DESCRIPTION
**Pull request by LFBarreto**
(Accounts): no accounts placeholder image loaded as react component

### Type

Code Quality Improvement

### Context

LL-3422

### Parts of the app affected / Test plan

No accounts placeholder. should affect mainly the bullrun tests

### CODE REVIEW

**Review by juan-cortes — DISMISSED** [review]
Duh! Nice, makes sense 😅

**Review by gre — CHANGES_REQUESTED** [review]
Can you make it a pure component so react don't have to compare the whole svg, component?

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
mmh any reason it's not passing CI?

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
### Bug found
Regression.
"Terms of use" modal shouldn't be displayed before the onboarding.
ezgif com-gif-maker

### How to reproduce
- Clean LL user data
- Start LL

### Expected behaviour
The "Terms of use" modal should be displayed after onboarding success screen (After the confetti)

**Review by Arnaud97234 — APPROVED** [review]

**Pull request merged**
