### PR TITLE
Terms of Use update pop-up 

### PR DESCRIPTION
**Pull request by thomasrogerlux**
## 🦒 Context (issues, jira)

[LIVE-1916]

## 💻  Description / Demo (image or video)

We wish to notify users properly when the Terms of Use gets updated, directly through Ledger Live. This PR add a new modal in the main `Default` component that will open when the `isAcceptedTerms` returns false and the user isn't in the onboarding. Closing the modal accepts the terms.

Screenshot from 2022-04-14 11-17-06

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

[LIVE-1916]: https://ledgerhq.atlassian.net/browse/LIVE-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by LFBarreto — APPROVED** [review]

**Review by ThomasLaforge — APPROVED** [review]
See you in 2042 for the bug of playwright 2042-01-01.
But it seems fair as we should switch on new tests framework before 2042 ^^

**Review by nabil-brn — CHANGES_REQUESTED** [review]
https://ledgerhq.atlassian.net/browse/LIVE-1916?focusedCommentId=185346

---
Ledger Live 2.41.3-sha.d50dc6cfb295dd791b01336d1fc5d0d833811615

**Review by ychen-ledger — APPROVED** [review]
Validated with: 

- LLD 2.41.3-sha.fe183d64b5db1dec42d40353157a4769c589f070
- MacOS Big Sur 11.4

**Review by nabil-brn — APPROVED** [review]
Approved for the merge requirements

**Pull request closed without merging**
