### PR TITLE
LL-3969 fix white screen bug

### PR DESCRIPTION
**Pull request by machard**
https://ledgerhq.atlassian.net/browse/LL-3969

remove node_modules/node-hid => it should show the nice error screen.

### CODE REVIEW

**Review by gre — APPROVED** [review]

**Review by nabil-brn — DISMISSED** [review]
image

This page should apply current theme (color).

---
3a3d2af0 (HEAD -> pr/machard/3329, machard/LL-3969) fix white screen bug

**Comment by gre** [comment]
No this shouldn't. We can't do it and that's what caused the bug. This is the critical error case and we don't access to level of user data we need to know if it's dark mode.

**Comment by nabil-brn** [comment]
Ok, I thought it was possible because I have this 8px margin in dark color 🤷‍♂️.

**Review by nabil-brn — APPROVED** [review]

**Comment by gre** [comment]
It's not critical to guarantee dark mode , this screen should hopefully not happen for users.

**Pull request merged**
