### PR TITLE
live-common @ 7.11.x + other lib bumps

### PR DESCRIPTION
**Pull request by gre**
Upgraded live-common with 2 past weeks work.

Check everything is still working fine.

Fixed:

- LL-1744: added a "BTC on BCH path" invalid path derivation https://github.com/LedgerHQ/ledger-live-common/pull/327 (see instructions)
- LL-1768: fixed amount serialization logic to handle text like `00000.123` https://github.com/LedgerHQ/ledger-live-common/pull/325
- whitelist only fiats that have a pair available. https://github.com/LedgerHQ/ledger-live-common/pull/328
- fixes HTTP 404 reorg on ETH (difficult to test) https://github.com/LedgerHQ/ledger-live-common/pull/326
- removed TaxToken https://github.com/LedgerHQ/ledger-live-common/pull/322

### CODE REVIEW

**Comment by gre** [comment]
@Arnaud97234 

- LL-1814 is probably on develop too. this is now fixed in this PR tho because we're only going to whitelist the fiat that have pair for now.
- LL-1816 are you sure it's a regression on this PR? not sure we changed anything on this.

**Comment by Arnaud97234** [comment]
> @Arnaud97234
> 
> * LL-1814 is probably on develop too. this is now fixed in this PR tho because we're only going to whitelist the fiat that have pair for now.
> * LL-1816 are you sure it's a regression on this PR? not sure we changed anything on this.

Bug also present on develop

**Comment by gre** [comment]
ok phew. if there is nothing else we could merge that and fix these in other PRs

**Comment by Arnaud97234** [comment]
> Upgraded live-common with 2 past weeks work.
> 
> Check everything is still working fine.
> 
> Fixed:
> 
> * LL-1744: added a "BTC on BCH path" invalid path derivation [LedgerHQ/ledger-live-common#327](https://github.com/LedgerHQ/ledger-live-common/pull/327) (see instructions)

Sending back from BTC (Custom) to BCH account results in receive on BTC (legacy) account

> * LL-1768: fixed amount serialization logic to handle text like `00000.123` [LedgerHQ/ledger-live-common#325](https://github.com/LedgerHQ/ledger-live-common/pull/325)
> * whitelist only fiats that have a pair available. [LedgerHQ/ledger-live-common#328](https://github.com/LedgerHQ/ledger-live-common/pull/328)
> * fixes HTTP 404 reorg on ETH (difficult to test) [LedgerHQ/ledger-live-common#326](https://github.com/LedgerHQ/ledger-live-common/pull/326)
> * removed TaxToken [LedgerHQ/ledger-live-common#322](https://github.com/LedgerHQ/ledger-live-common/pull/322)

**Comment by gre** [comment]
🎊

**Pull request merged**
