### PR TITLE
LL-448 segwit parsing

### PR DESCRIPTION
**Pull request by amougel**
This will allow any bitcoinlike altcoin account to spend utxo received from segwit transactions.

### CODE REVIEW

**Comment by meriadec** [comment]
:thinking_face:

**Comment by gre** [comment]
I also don't understand the fix. it's touching the code of "signAndBroadcast" how does this would help for "**receive** segwit transactions"

**Comment by amougel** [comment]
I meant that right now, a user receiving a segwit transaction is not able to spend it because of the reception of this output because he is not able to parse it properly. So the fix will have an effect o the sending flow indeed.

**Comment by meriadec** [comment]
@amougel if you don't mind, can you put a comment next to the `true` for clarity?

**Comment by gre** [comment]
@amougel ok, i've updated the description because it was not saying that ;)

**Pull request merged**
