### PR TITLE
[add] adds ubiq

### PR DESCRIPTION
**Pull request by drewrothstein**
* Adds `ubiq` now that https://github.com/LedgerHQ/ledger-live-common/pull/56 is merged.

### Type

Feature: Adds `ubiq`.
Cleanup: Alpha-sorts the lists, adds explicitness to README, updates diagram to show JS implementation.

### Context

Requested: https://github.com/LedgerHQ/ledger-live-desktop/issues/1031

### Parts of the app affected / Test plan

That `ubiq` is now available and functional.
Ran `yarn test` and it passes:
```
ledger-live-desktop (drew/add_ubiq)$ yarn test
yarn test v0.27.5
$ jest
 PASS  src/helpers/db/db.spec.js
 PASS  src/migrations/migrations.spec.js (6.476s)

Test Suites: 2 passed, 2 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        7.456s
Ran all test suites.
Done in 10.73s.
```

Happy to do more testing, et cetera; First PR in this repo.

### CODE REVIEW

**Comment by drewrothstein** [comment]
For the tests to pass (and for this to work), we will need a version bump of `LedgerHQ/ledger-live-common` with the PR (now on `master`) https://github.com/LedgerHQ/ledger-live-common/pull/56 included.

I am happy to submit a PR to do that but I assume you have some process for bumping/publishing that and then bumping the version here?

**Comment by gre** [comment]
to support ubiq, I think there will be a bit more work than this.
it's not just about enabling the visibility of the currency in the list but also the actual implementation of the blockchains interface. what we call a "bridge" here: https://github.com/LedgerHQ/ledger-live-desktop/tree/develop/src/bridge

for instance, Ripple implementation use "RippleJSBridge" which is backed by ripple-lib and ripple's API.
I don't have a clear knowledge of what Ubiq imply. but it seems that so far it was relying on using a website with the ledger? https://support.ledgerwallet.com/hc/en-us/articles/115005459725-Install-and-use-Ubiq-UBQ- so i guess maybe Ledger Live could use ubiq api 🤔  


anyway, it's not that trivial as this PR.

**Comment by drewrothstein** [comment]
Cool, I will take a look!

**Comment by drewrothstein** [comment]
Taking a brief look, it looks like the `pyruswallet`: https://github.com/ubiq/pyruswallet, uses a hard-coded address that I assume they run: https://github.com/ubiq/pyruswallet/blob/mercury/json_relay_php/api.php#L4.

It looks like a lot of `Ethereum.js` and `EthereumJSBridge.js` would just be copied into a `Ubiq.js` and `UbiqJSBridge.js`.

Trying to understand all of the pieces here- what are you running at https://explorers.api.live.ledger.com?  Trying to understand the flow from `Ethereum.js` > `Ledger.js` > `constants.js` and what the intent of that hosting actually is.

Cheers-

**Comment by gre** [comment]
I don't think we have a Ubiq explorer on our end as it's a community baked project, so this is probably where the different will be. Need to figure out what API to hit.

**Comment by iquidus** [comment]
Hey there, currently for pyrus/MEW/mycrypto we run the nodes (which in turn are used for ledger via browser support). More than happy to spin up nodes/API's required for ledger live, or add any required API calls to existing explorers.

**Comment by drewrothstein** [comment]
@iquidus very awesome.  @gre what requirements from an infra. point-of-view are required on your side for Ledger?  Do you have any availability/uptime requirements that @iquidus would need to take into consideration for running a node/API?

**Comment by gre** [comment]
we'll reopen when the PR is fully ready (infra, libcore). this require a business decision from Ledger side. Feel free to contact @FabriceDautriat .

**Pull request closed without merging**
