### PR TITLE
LIVE-1391 Show NanoSP by default

### PR DESCRIPTION
**Pull request by juan-cortes**
## 🦒 Context (issues, jira)
https://ledgerhq.atlassian.net/browse/LIVE-1391

## 💻  Description / Demo (image or video)

Enable the Ledger Nano S Plus by default on the application, without requiring the SHOW_NANOSP flag like we needed up until now. This means the device should be available during onboarding and detected when plugged in (this last part was already the case). Make sure the app shows the device without needing the flag. All other functionality was tested in the specific PRs.

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

### CODE REVIEW

**Review by thomasrogerlux — APPROVED** [review]

**Comment by juan-cortes** [comment]
Come CI be nice for once

**Comment by juan-cortes** [comment]
Waiting for CI again because that's my life now

**Pull request merged**
