### PR TITLE
LL-1825 See a portfolio of a specific asset

### PR DESCRIPTION
**Pull request by juan-cortes**
### Screenshots
image
image
image

### Type

Feature.

### Context

https://ledgerhq.atlassian.net/browse/LL-1825

https://ledgerhq.atlassian.net/browse/LL-1600

### Parts of the app affected / Test plan

The whole new page and affected blocks from the portfolio. Special atention to the graph.
There's a known issue that would be addressed on a separate pr for the green and red arrows for delta.

---

#### NOTE THAT THIS INCLUDES THE WORK FROM @pbondoer ON LL-1600
This means that on this pr we no longer have the greeting on the portfolio, and we have the new periodicity tabs and design integrated too.

### CODE REVIEW

**Comment by gre** [comment]
definitely feels like it need a wording review. the "you can now click on.." text feels weird.

**Comment by juan-cortes** [comment]
Last commit addresses LL-1858 and LL-1859 by filtering the tokens if the flag is set and by adding the context menu to the token lists everywhere. This last one has been present ever since we added the initial context menu so good catch @Arnaud97234 let me know if you find anything else.

Pending @dasilvarosa check

**Comment by juan-cortes** [comment]
I think the two bugs are more related to the balance summary block and I would rather address them on a separate pr, but I'll take a look in the morning anyway 👍

**Comment by gre** [comment]
if possible please fix in this PR because we merged both work into one and i would prefer we don't merge inconsistency work in develop. 🙏

**Comment by juan-cortes** [comment]
The mismatch between percentage and value is fixed on the live-common pr, the other one about the missing percentage is not related to this pr at all.

**Comment by gre** [comment]
`develop` can be rebased as it contains latest live-common

**Comment by juan-cortes** [comment]
@gre hover states added, ready for this "testing build"

**Comment by juan-cortes** [comment]
>     * account name to not uppercase on erc20 account row
> 
> 
> Capture d’écran 2019-09-10 à 11 19 30
> 
>     * bug when you try to do "Send" with the "..." action on a erc20 account row

Both addressed on latest commit

**Pull request merged**
