### PR TITLE
LL-4442 add day in portfolio graph

### PR DESCRIPTION
**Pull request by machard**
https://ledgerhq.atlassian.net/browse/LL-4442

needs https://github.com/LedgerHQ/ledger-live-common/pull/1030

### CODE REVIEW

**Comment by gre** [comment]
@machard you can continue from develop & try to put it back. @nabil-brn found issue reported on the mentionned PR that you can find again. I also experienced the issue

**Comment by machard** [comment]
i wait for https://github.com/LedgerHQ/ledger-live-desktop/pull/3503 to regenerate the snapshots

**Comment by gre** [comment]
@machard did you manage to reproduce Nabil's issue tho? the fact when you hover you only see 2 location on the chart. => i actually wonder if it was actually happening due to ongoing isutation with our API. i would recommend to try to simulate "holes" in our API. typically we used to have the issue i mention here https://github.com/LedgerHQ/ledger-live-common/pull/1044

it would be weird, but i wonder if we correctly build up the graph data when the countervalues isn't available 🤔  @JunichiSugiura do you know?

**Comment by machard** [comment]
@gre yep i checked, https://github.com/LedgerHQ/ledger-live-desktop/pull/3514/commits/31d4f05fdd86e315636187e2c88c5963356b5e4e#diff-dcc832dbca6c35a82da8ffd07f844677857ac8a5e1e4b1d79aa920ca1592c4c8R102 fix it.

Capture d’écran 2021-02-03 à 17 39 57

**Comment by machard** [comment]
oké

**Review by valpinkman — DISMISSED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
@machard Values are missing on X axis. It should scale by hour.

image

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
Day graph is present on account page and repartition. The scale is incorrect when graph is Weekly, we show 12AM instead of the date.

image

**Review by Arnaud97234 — APPROVED** [review]

**Review by Arnaud97234 — APPROVED** [review]

**Comment by gre** [comment]
this will be addressed by **https://github.com/LedgerHQ/ledger-live-desktop/pull/3642**

**Pull request closed without merging**
