### PR TITLE
LL-6591 Hide buy button when currency isn't supported on send flow

### PR DESCRIPTION
**Pull request by JunichiSugiura**
### Type

Bug Fix

### Context

[LL-6591](https://ledgerhq.atlassian.net/browse/LL-6591)

### Parts of the app affected / Test plan

BSC send -> Amount step

### CODE REVIEW

**Review by gre — COMMENTED** [review]
ticket also mention a fix for Sell button

**Review by gre — CHANGES_REQUESTED** [review]
please add fix for sell as scoped in ticket. thx

**Review by juan-cortes — APPROVED** [review]
lgtm

**Review by gre — APPROVED** [review]
ok i've tested and there are no longer any issue on sell 🤔

**Review by ychen-ledger — APPROVED** [review]
Validated with:

- MacOs Big Sur version 11.4
- ledger live 2.32.0

**Pull request merged**
