### PR TITLE
LL-7223 add watermark to nightly version

### PR DESCRIPTION
**Pull request by valpinkman**
## 🦒 Context (issues, jira)

[LL-7223]

## 💻  Description / Demo (image or video)

CleanShot 2021-09-22 at 14 54 52@2x
watermark on the top of the sidebar. 
yes it here. 
i swear. 
look closely. 

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

[LL-7223]: https://ledgerhq.atlassian.net/browse/LL-7223

### CODE REVIEW

**Review by achabrolin-ledger — COMMENTED** [review]
I don't know what's the purpose of this watermark, but if the goal is to make it obvious to a user of such build that he is using a nightly (thus unstable) version of the app, I feel like as of today the watermark is too subtle (not visible / obvious enough).

In this cas I would rather suggest a sort of red banner (with the version inside why not) in the top left corner of the app in order to make it more obvious

**Review by juan-cortes — APPROVED** [review]

**Comment by achabrolin-ledger** [comment]
> I don't know what's the purpose of this watermark, but if the goal is to make it obvious to a user of such build that he is using a nightly (thus unstable) version of the app, I feel like as of today the watermark is too subtle (not visible / obvious enough).
> 
> In this cas I would rather suggest a sort of red banner (with the version inside why not) in the top left corner of the app in order to make it more obvious

We could think of something like that (ugly but visible). We could polish the CSS if need be 🤷‍♂️ 
<details>
 <summary> Example 📷  </summary>


example

</details>

**Comment by juan-cortes** [comment]
@achabrolin-ledger it's also about customer support identifying a user issue when they provide a screenshot we can know if it's from a nightly or not. if we only mark the top left, the user can take a screenshot of the impacted part of the screen and we wont know if it's a nightly or not. I agree maybe it's too subtle but again, we want the users to be able to use the app without hating it, they/we are helping us find bugs and debug

**Comment by achabrolin-ledger** [comment]
> @achabrolin-ledger it's also about customer support identifying a user issue when they provide a screenshot we can know if it's from a nightly or not. if we only mark the top left, the user can take a screenshot of the impacted part of the screen and we wont know if it's a nightly or not. I agree maybe it's too subtle but again, we want the users to be able to use the app without hating it, they/we are helping us find bugs and debug

Ok thanks for the context, I thought it was for internal use only but if it's also used by external end users, makes sense to have it less obvious and displayed on the whole screen 👌

**Review by achabrolin-ledger — APPROVED** [review]

**Pull request merged**
