### PR TITLE
Bump live-common 19.4.0

### PR DESCRIPTION
**Pull request by gre**
- https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.3.0
- https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.4.0
- minor upgrade of some deps

### CODE REVIEW

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
Seed TRC20 is present twice in the token list
image

**Comment by gre** [comment]
:(

**Comment by gre** [comment]
I don't understand how this is possible. do you know @FabriceDautriat ? is there a SEED on trc10 maybe?

**Comment by Arnaud97234** [comment]
> I don't understand how this is possible. do you know @FabriceDautriat ? is there a SEED on trc10 maybe?

@gre It seems that "Seed" token has been moved from trc10 to trc20 last year.

**Comment by Arnaud97234** [comment]
- [] update ERC20 & TRC20 lists
- [x] LL-5160 (Polkadot) Display correct tx type for send max
- [x] LL-5118 Deduct payout fees from swap operation history
- [x] LL-4832 display actual content of error
- [x] Stellar JS

**Review by Arnaud97234 — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
