### PR TITLE
electron 9

### PR DESCRIPTION
**Pull request by valpinkman**

### CODE REVIEW

**Comment by valpinkman** [comment]
HODL again because bullrun does not work

**Comment by valpinkman** [comment]
@nabil-brn it's been rebased and updated, can you test it again ?

**Comment by valpinkman** [comment]
> The app is not displayed anymore, errors are thrown while starting with `yarn dist` and `yarn start`.
> 
> ```
> Ledger Live 2.8.0
> Error: Invalid header: Does not start with Cr24    at crxToZip (/Users/nbourenane/workspace/ledger-live-desktop/node_modules/unzip-crx/dist/index.js:32:15)    at /Users/nbourenane/workspace/ledger-live-desktop/node_modules/unzip-crx/dist/index.js:57:32    at callHanler (/Users/nbourenane/workspace/ledger-live-desktop/node_modules/yaku/lib/yaku.js:719:16)
>     at tryCatcher (/Users/nbourenane/workspace/ledger-live-desktop/node_modules/yaku/lib/yaku.js:436:32)
>     at /Users/nbourenane/workspace/ledger-live-desktop/node_modules/yaku/lib/yaku.js:575:38
>     at flush (/Users/nbourenane/workspace/ledger-live-desktop/node_modules/yaku/lib/yaku.js:478:17)
>     at processTicksAndRejections (internal/process/task_queues.js:76:11)
> (node:91202) UnhandledPromiseRejectionWarning: Error: Image could not be created from /Users/nbourenane/workspace/ledger-live-desktop/.webpack/build/icons/icon.png
>     at createMainWindow (webpack-internal:///./src/main/window-lifecycle.js:98:16)
>     at App.eval (webpack-internal:///./src/main/index.js:121:98)
> (node:91202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:91202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:91202) ExtensionLoadWarning: Warnings loading extension at /Users/nbourenane/Library/Application Support/Electron/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd: Unrecognized manifest key 'commands'. Unrecognized manifest key 'homepage_url'. Unrecognized manifest key 'page_action'. Unrecognized manifest key 'short_name'. Unrecognized manifest key 'update_url'. Permission 'notifications' is unknown or URL pattern is malformed. Permission 'contextMenus' is unknown or URL pattern is malformed. Permission 'tabs' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
> ```
> 
> [70a1916](https://github.com/LedgerHQ/ledger-live-desktop/commit/70a1916f6624aadb4445e4ee3692e9c9d592071b) (HEAD -> electron-9, val/electron-9) bump deps and lint fixes

It seems to be an error with the devtools extensions not being supported anymore, I think there has been a fix about it but I do need to check

**Comment by gre** [comment]
`Cannot read property 'background' of undefined`

**Comment by gre** [comment]
Status?

**Review by LFBarreto — APPROVED** [review]
:confetti_ball: :nine:

**Review by nabil-brn — APPROVED** [review]

**Pull request merged**
