### PR TITLE
improved container setup + split tests + swap tests + parallel run

### PR DESCRIPTION
**Pull request by machard**
It's an attempt to make the launch of the electron webdriver container faster locally.
The container build or no build has been improved.

~~Now I'm trying to just install native dependencies in the container when they change, instead of all the deps whenever package.json/yarn.lock change.~~ => I failed. It's still faster now.

run `yarn start-electron-webdriver` once, wait, kill it, relaunch and it will be faster.

### CODE REVIEW

**Review by gre — DISMISSED** [review]

**Comment by machard** [comment]
well well i don't understand

**Comment by machard** [comment]
the `mockDeviceEvent` method tends to fail sometimes, it happens to me locally as well, not sure why but that's annoying..

**Comment by machard** [comment]
looks like it's working now

**Comment by machard** [comment]
It works BUT..
I think the image thing is a quick and easy win to detect changes and regressions but we need to mock more things and be careful with timing:
current problems https://i.imgur.com/kIpg8p7.png https://i.imgur.com/xNNmul0.png https://i.imgur.com/NqnYagt.png
previous examples : https://i.imgur.com/9ZvIJCv.png https://i.imgur.com/WVPloL6.png https://i.imgur.com/V1fKC6m.png

after a quick check:
- firmware update api mock
- countervalue api mock
- computer date
- synchronize mock (api?)
- quotes timers mocks

**Pull request closed without merging**
