### PR TITLE
Feat  LIVE-1630 lld update ctas style

### PR DESCRIPTION
**Pull request by LFBarreto**
## 🦒 Context (issues, jira)
[LIVE-1630]

- Updated market buy/swap ctas style
- Updated style of account page

## 💻  Description / Demo (image or video)

https://user-images.githubusercontent.com/11752937/157708489-c877db1b-73f9-4303-9a52-25fcfacbcd2d.mp4

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

[LIVE-1630]: https://ledgerhq.atlassian.net/browse/LIVE-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by juan-cortes — CHANGES_REQUESTED** [review]

**Review by thomasrogerlux — APPROVED** [review]
Code looks good

**Pull request merged**
