### PR TITLE
improved container setup + split tests + swap tests + parallel run + overall stability

### PR DESCRIPTION
**Pull request by machard**
**!! Todo before merging !!**
replace `pull_request` by `pull_request_target` in ci.yml

### CODE REVIEW

**Comment by machard** [comment]
current state: https://github.com/LedgerHQ/ledger-live-desktop/pull/3301#issuecomment-733148022

**Comment by machard** [comment]
`
sdsd
sdsd
`

**Comment by machard** [comment]
Yay.
So 3 problems:
- the scrollbar
- countervalues
- date

**Comment by machard** [comment]
- navbar issue => hide scrollbar OR electron/electron#8314 (comment)
- timemachine => does not work with moment. I think its because of https://github.com/schickling/timemachine/pull/4/files#diff-d094f1dfbee01657e151c48ac7f5cce35efb750426c93a0d1990c74accafa31dR77

**Comment by machard** [comment]
- navbar ?
- total balance issue ?

**Comment by machard** [comment]
success but I need to fix the following steps in order to get the green cross

**Comment by machard** [comment]
ready for merge!
**!! Todo before merging !!**
replace `pull_request` by `pull_request_target` in ci.yml. this will break the CI on this PR when done and this is the reason the pull_request_target type checking check is currently marked as failed

**Comment by gre** [comment]
I don't understand the comment, isn't it already the case ?

 https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/.github/workflows/ci.yml#L3

**Comment by machard** [comment]
in develop yes, but in this PR, in order to test I had to change it, https://github.com/LedgerHQ/ledger-live-desktop/pull/3324/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR3

**Pull request merged**
