### PR TITLE
LL-6654 - Rebrand - Tab Components

### PR DESCRIPTION
**Pull request by jelbaz-ledger**
Add Tab components (named "Graph" and "View" in Figma).

https://user-images.githubusercontent.com/86958797/129890497-ee3b6f05-d509-46b4-8319-10e49539bb61.mp4

### Type

UI

### Context

[LL-6654]

[LL-6654]: https://ledgerhq.atlassian.net/browse/LL-6654

### CODE REVIEW

**Review by jgiamporcaro-ledger — APPROVED** [review]
LGTM. Thanks for the `React.PropsWithChildren` tips, I'll use it more often

**Comment by ggilchrist-ledger** [comment]
Would it be possible to have the ability to add the icons in the Stories to match the Figma designs? @jelbaz-ledger

**Comment by jelbaz-ledger** [comment]
> Would it be possible to have the ability to add the icons in the Stories to match the Figma designs?

Sure, should be good now! 👍 

Capture d’écran 2021-08-20 à 13 58 54

**Comment by ggilchrist-ledger** [comment]
LGTM @jelbaz-ledger

**Review by ggilchrist-ledger — APPROVED** [review]

**Pull request merged**
