### PR TITLE
LL-9044 Change plugin rendering on Manager

### PR DESCRIPTION
**Pull request by juan-cortes**
## 🦒 Context (issues, jira)
https://ledgerhq.atlassian.net/browse/LL-9044

## 💻  Description / Demo (image or video)
Using the newly exposed `type` for our applications (temporarily leveraging an unused `description` field) we are now able to show a different wording/cta for plugins on the manager. When the changes on the backend API rollout, we will have a proper field to discern which app type we need to render, until then, this is the best we can do.

image

image

## 🖤  How to test this
- Enter the manager
- Search for a plugin (ie paraswap)
- Check the rendering matches the screenshots below
- If installed, click on the "Go to App" cta
- It is expected that we should navigate out of the manager and into the discover section

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]

**Review by tlaforge-ledger — APPROVED** [review]

**Comment by juan-cortes** [comment]
Mocks break for some reason, need to check monday.

**Comment by juan-cortes** [comment]
I dont understand you ci, I dont understand you at all

**Comment by juan-cortes** [comment]
Please kill me

**Pull request merged**
