### PR TITLE
[COIN-464] Polkadot: add note in first bond

### PR DESCRIPTION
**Pull request by henri-ly**
### Type

UI 

### Context

https://ledgerhq.atlassian.net/browse/COIN-464

### Parts of the app affected / Test plan

Polkadot add note in the first bond where you explain what is the reward destination

### CODE REVIEW

**Comment by valpinkman** [comment]
The PR seems ok however there is a warning in the test saying you are using several instances of 2 packages
```
console.warn
  Multiple instances of @polkadot/wasm-crypto detected, ensure that there is only one package in your dependency tree.
  	3.2.2	/home/runner/work/ledger-live-desktop/ledger-live-desktop/node_modules/@polkadot/metadata/node_modules/@polkadot/wasm-crypto
  	3.2.2	/home/runner/work/ledger-live-desktop/ledger-live-desktop/node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto

  at detectPackage (node_modules/@polkadot/types/node_modules/@polkadot/util/detectPackage.js:86:13)
  at Object.<anonymous> (node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/detectPackage.js:35:25)
  at Object.<anonymous> (node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/index.js:12:1)

console.warn
  Multiple instances of @polkadot/util-crypto detected, ensure that there is only one package in your dependency tree.
  	5.4.4	/home/runner/work/ledger-live-desktop/ledger-live-desktop/node_modules/@polkadot/metadata/node_modules/@polkadot/util-crypto
  	5.4.4	/home/runner/work/ledger-live-desktop/ledger-live-desktop/node_modules/@polkadot/types/node_modules/@polkadot/util-crypto

  at detectPackage (node_modules/@polkadot/types/node_modules/@polkadot/util/detectPackage.js:86:13)
  at Object.<anonymous> (node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/detectPackage.js:35:25)
  at Object.<anonymous> (node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/index.js:9:1)
```

Is this expected ?

**Comment by henri-ly** [comment]
Weird it shouldn't be expected because nothing it's related by this in this PR. I'll try to look what is happening in live-common

**Comment by haammar-ledger** [comment]
Fixed by https://github.com/LedgerHQ/ledger-live-desktop/pull/3567

**Comment by gre** [comment]
shipped through mashup pr

**Pull request closed without merging**
