### PR TITLE
Improve update wording

### PR DESCRIPTION
**Pull request by dasilvarosa**
This should address some UX problems during the update.

**Note at implementing dev:** 
- [ ] Put `Processing` in bold style in the _mcuSecond_ key.

### CODE REVIEW

**Comment by gre** [comment]
@juan-cortes  if you can give a second 👁  to this, but there is no structural change (like new arguments in wording) so it should be smooth and we can merge it

**Comment by meriadec** [comment]
@dasilvarosa can you amend your commit to use spaces instead of tabs? :pray:

**Comment by dasilvarosa** [comment]
@meriadec Done. Thanks!

**Comment by dasilvarosa** [comment]
Too bad it's already merged without putting the `mcuSecond` key in bold!

**Pull request merged**
