### PR TITLE
Add ledger live version in header and websocket param

### PR DESCRIPTION
**Pull request by gre**
this is in HODL because waiting our API to accept new headers as part of Access-Control-Allow-Headers

### CODE REVIEW

**Comment by meriadec** [comment]
@pollastri-pierre is it OK now? I recently saw cors-related commits

**Comment by gre** [comment]
we'll need to have QA team double-check this too ;)

**Comment by Arnaud97234** [comment]
**Test result**

Object {X-LedgerLiveVersion: "1.2.0"}
➡📡  GET https://explorers.api.live.ledger.com/blockchain/v2/eth/blocks/current Object {type: "network"}

XMLHttpRequest cannot load https://explorers.api.live.ledger.com/blockchain/v2/eth/blocks/current. Request header field X-LedgerLiveVersion is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by gre** [comment]
so it means worked on backend side is not ready. cc @pollastri-pierre

**Comment by gre** [comment]
we'll reopen the discussion internally on the need of such header

**Pull request closed without merging**
