### PR TITLE
Coin 1145 display fees desktop

### PR DESCRIPTION
**Pull request by henri-ly**
### Type

UI add info

### Context

https://ledgerhq.atlassian.net/browse/COIN-1145

### Parts of the app affected / Test plan

Change on modal of all confirmation, it should not be affected by any other coin + refacto of Info box

### CODE REVIEW

**Review by rjarasson-ledger — DISMISSED** [review]

**Review by gre — APPROVED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
The fees amount is still missing for the Nominate operation
Screenshot 2021-02-09 at 17 37 31

**Comment by henri-ly** [comment]
Weird, it's probably because your live-common is not up to date ? there's no dump yet with live-common and the fees field, you will need to yalc it I guess

**Comment by rjarasson-ledger** [comment]
@Arnaud97234 This modal is scrollable (as you can see in your screenshot) - the field should be below.

The fees are not part of the transaction to be validated on device, but set by the network on broadcast.
So we added an infobox to inform that the user will not see it on device even though it's indicated.

**Review by Arnaud97234 — APPROVED** [review]

**Comment by gre** [comment]
shipped through mashup pr

**Pull request closed without merging**
