### PR TITLE
live-common 18.6.0 + 18.7.0 + libcore

### PR DESCRIPTION
**Pull request by gre**
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v18.6.0
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v18.7.0

### CODE REVIEW

**Comment by Arnaud97234** [comment]
- [ ] LL-4621 No longer export dev mode setting (#1084)
- [ ] disable XSN v3 experimental until BACK-1603
- [ ] LL-4667 Stargate: check tx amount before getting gas estimate #1077
- [ ] Remove the amount update from Cosmos rewards spec (#1066)
- [ ] LL-4672 Allow new apps to pass the quitApp support test (#1080)
- [ ] fix(Polkadot): fix election status threshold + add ENV to tweak it - COIN-1376
- [ ] fix(Polkadot): ensure Polkadot prefix is also valid in address - COIN-1379

**Comment by valpinkman** [comment]
@gre screenshot to be updated

**Comment by nabil-brn** [comment]
**18.6.0**
- [x] Remove the amount update from Cosmos rewards spec (#1066)
- [ ] fix(Polkadot): fix election status threshold + add ENV to tweak it - COIN-1376

**18.7.0**
- [ ] scanAccounts to not fail on older device versions (#1089)
- [ ] Introduce Account#used boolean to track account "exists" (#1069)
- [ ] Fixes cosmos hole problem on Add Account
- [ ] Update XRPL endpoint to alternative (#1087)

---
3970a5998 (HEAD -> live-common-18-6-0, gre/live-common-18-6-0) Merge branch 'develop' into live-common-18-6-0

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
Issue on send max Cosmos: https://ledgerhq.atlassian.net/browse/LL-4856

**Review by Arnaud97234 — APPROVED** [review]

**Review by nabil-brn — APPROVED** [review]

**Review by juan-cortes — APPROVED** [review]

**Pull request merged**
