### PR TITLE
Live common 19.7.x

### PR DESCRIPTION
**Pull request by gre**
mid-sprint release of live-common & libs upgrade.

The live-common upgrades includes:

- https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.7.0
- fixes #3642 LL-2542 Portfolio V2 & all time range support
- fixes https://github.com/LedgerHQ/ledger-live-desktop/pull/3782 (see PR to get all ticket numbers)

---

Plan: we may possibly want to do all possible QA on this PR and at last minute if we are good, we remove in live-common the deprecated stuff (remove the old balanceHistory field + drop the non v2 portfolio stuff + major bump of live-common + make Date non optional) and do one last check.

### CODE REVIEW

**Comment by Arnaud97234** [comment]
- [ ] LL-2542 Portfolio V2 & all time range support
- [ ] LL-4947 - update electron builder
- [ ] erc20 update
- [ ] LL-4552
- [ ] LL-5359
- [ ] LL-5360
- [ ] LL-5151 – portfolio & countervalues optimizations
- [ ] LL-5401 Workaround for Stellar SDK not using the correct URL

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
Bugs founds:
https://ledgerhq.atlassian.net/browse/LL-5433

**Comment by gre** [comment]
electron-builder rollbacked some issue

**Review by JunichiSugiura — DISMISSED** [review]

**Review by Arnaud97234 — COMMENTED** [review]
@gre For me it's a GO, waiting for @nabil-brn to confirm then we can merge

**Review by Arnaud97234 — APPROVED** [review]

**Pull request merged**
