### PR TITLE
edit account name in place

### PR DESCRIPTION
**Pull request by machard**
Capture d’écran 2020-10-20 à 14 47 34

### Type

UI/UX Polish

### Context

https://ledgerhq.atlassian.net/browse/LL-3534

### Parts of the app affected / Test plan

You are now able to edit the account name directly by clicking on the account name in the header

### CODE REVIEW

**Comment by machard** [comment]
I went with the contentEditable method (which does not play super well with react)

**Review by gre — DISMISSED** [review]

**Review by nabil-brn — CHANGES_REQUESTED** [review]
Unfortunately, the account header (or field now) is too short imo, it added an ellipsis to all my accounts.

image
image

---
2.14.0-sha.3e583d9-win.exe

**Comment by machard** [comment]
@nabil-brn i've updated and on the smaller size it looks like
Capture d’écran 2020-10-22 à 17 33 48
Capture d’écran 2020-10-22 à 17 33 54

**Review by nabil-brn — APPROVED** [review]
✓ QA-ed

---
2.15.0-sha.6363e48-win.exe

**Review by gre — APPROVED** [review]

**Pull request merged**
