### PR TITLE
LIVE-403 tooltip price value shortened if too long

### PR DESCRIPTION
**Pull request by cgrellard-ledger**
## 🦒 Context (issues, jira)

[LIVE-403]

## 💻  Description / Demo (image or video)

The price was overflowing the graph tooltip container if it was too long. This PR adresses that issue by using the `shorten` option in LLC's `counterValueFormatter`.

**Before:**
Screenshot 2022-02-21 at 12 01 50

**After:**

Screenshot 2022-02-21 at 12 02 44

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

[LL-403]: https://ledgerhq.atlassian.net/browse/LL-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIVE-403]: https://ledgerhq.atlassian.net/browse/LIVE-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by juan-cortes — CHANGES_REQUESTED** [review]
Please fix your pr, add a description, and a screenshot of the resulting solution

**Comment by ofreyssinet-ledger** [comment]
taking over as @cgrellard-ledger is off this week

**Review by OlivierFreyssinet — APPROVED** [review]

**Review by juan-cortes — APPROVED** [review]
lgtm

**Review by nabil-brn — APPROVED** [review]
✔️ Tested

---
b89b4e88b (HEAD -> bugfix/LIVE-403-market-text-overlap-tooltip, ledger/bugfix/LIVE-403-market-text-overlap-tooltip) LIVE-403 tooltip price value shortened if too long

**Comment by ofreyssinet-ledger** [comment]
thanks @nabil-brn !

**Pull request merged**
