### PR TITLE
LIVE-968 - Fix ticker overlapping the swap button in market page

### PR DESCRIPTION
**Pull request by thomasrogerlux**
## 🦒 Context (issues, jira)

[LIVE-968]

## 💻  Description / Demo (image or video)

The ticker overlaps the buy and swap buttons in small screen size because the flex-basis of the second column is set too small.

#### Video
https://user-images.githubusercontent.com/23487649/155300449-5acbf76b-df78-4221-9732-d38cd2e387d7.mp4

Before:
Screenshot from 2022-02-21 09-21-01

After:
Screenshot from 2022-02-21 09-21-15

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

[LIVE-968]: https://ledgerhq.atlassian.net/browse/LIVE-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nparigi-ledger — APPROVED** [review]

**Comment by ofreyssinet-ledger** [comment]
In the second screenshot the rows are overflowing to the right ?

**Review by juan-cortes — APPROVED** [review]
Assuming this works on the smallest window size, but that's something for QA to validate

**Review by nabil-brn — APPROVED** [review]
Tested ✔️

image
---
35dc02c98 (HEAD -> bugfix/LIVE-968-ticker-overlap-swap-button, origin/bugfix/LIVE-968-ticker-overlap-swap-button) Fix really small screens

**Pull request merged**
