### PR TITLE
Ability to drag & drop accounts in main sidebar

### LINKED ISSUE #1154: Change the order of accounts by dragging them
- [x] I have checked this feature was not yet requested.

It would be great to have a feature where you can change the order of all your accounts by just dragging them.

#### Part of the application
The left part "accounts" of the screen.
The accounts part on the portfolio page

### LINKED ISSUE #1317: ledger live  - be able to reorganize and drag  accounts already created on the left sidebar
- [ ] I have checked this feature was not yet requested.

### **Issue related to the left sidebar in the App.**

right now if I add any new account btc, ltc or another one, this account goes to the end of the left sidebar

would be nice this account was add bellow of the coin shes belong not random as now.

**case 1:**
example: on this sample I have 2 btc accounts, after I create the third one, the account goes to the end of the sidebar, very bad to find the account, imagine someone having 100 or 1000 accounts (wallets adresses) , would be good to have it per coin?

**so for example:** 

bitcoin accounts = and show all bitcoins accounts
litecoin accounts = and show all litecoins accounts

don't need change much  the application color, could be using the dark and light colours already using on the app.

so the bitcoins will be a dark bg and litecoin a ligther one.

**case 2:** 
just organize new account created to be insert bellow the last one created according of the coin.

sample: I have 3 btc accounts if I create another one goes bellow the other 2 btc accounts and not to the end.

**case 3:**
 be able to move the accounts in the side bar like draggable , so I could move  the accounts and leave wherever i want top, middle, bottom

like that:
https://jqueryui.com/draggable/

#### Part of the application

sidebar

### PR DESCRIPTION
**Pull request by meriadec**
Closes #1154
Closes #1317

i think the title explain well.

reorder

### CODE REVIEW

**Comment by meriadec** [comment]
¯\_(ツ)_/¯

**Comment by meriadec** [comment]
¯\\_(ツ)_/¯

**Comment by gre** [comment]
I ever wonder if there will be such need to "sort yourself the accounts" if we always have account sorted by a criteria. what is the usecase for ordering things yourself 🤔

**Comment by meriadec** [comment]
Convenience, asked multiple times, easy to implement, and easy to cohabit with other sort criterias ("custom" taking precedence over other criterias if set).

I'll recommend to let user free to choose.

**Pull request closed without merging**
