### PR TITLE
Mashup/2.23

### PR DESCRIPTION
**Pull request by machard**
https://github.com/LedgerHQ/ledger-live-desktop/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.23

### CODE REVIEW

**Comment by gre** [comment]
thanks @machard

**Review by gre — APPROVED** [review]

**Review by nabil-brn — COMMENTED** [review]
- [x] LL-4564 Send amount error message updated  QA
- [x] LL-4524 add firmware update step for the new "updating" phase
- [x] Align how isConfirmed is checked  QA
- [x] LL-4514 - Wording for ledger status  QA
- [x] Coin 1145 display fees desktop  QA (approved by Arnaud already in related pr)
- [x] chore(deps): upgrade @polkadot/react-identicon to 0.69.1  QA
- [x] fix(Polkadot): remove transferAmount in OperationsList - LL-4435  QA
- [ ] [COIN-464] Polkadot: add note in first bond 
- [x] COIN-1349 Update one help page URL for Polkadot  QA
- [ ] Fixes cosmos issues 

---
2.22.0-sha.9fabcba69c2c4129fb14d8d65310a5f12f3f28be-win.exe.zip

**Comment by nabil-brn** [comment]
❌ Fixes cosmos issues

I've no operation history.

---
2.22.0-sha.9fabcba69c2c4129fb14d8d65310a5f12f3f28be-win.exe.zip

**Comment by gre** [comment]
merging this to trigger again the crowdin. if validating continues, let's do on develop.

**Pull request merged**
