### PR TITLE
tap bot to inform that the bug was fixed

### LINKED ISSUE #980: Cashaddr format for Bitcoin Cash
#### Ledger Live Version and Operating System

- Ledger Live **version_here**
- Platform: **windows OR mac OR linux**

### PR DESCRIPTION
**Pull request by gre**
@chaintip fixes #980

This PR is to inform the bot that https://github.com/LedgerHQ/ledger-live-desktop/pull/3120 have finally fixed #980
the small amount of the bounty will be used in Ledger Live for more testing 🚀  and will feed our own live-common 🤖 bot =)

### CODE REVIEW

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#980](http://github.chaintip.org/LedgerHQ/ledger-live-desktop/issues/980) first, @gre will claim the `0 BCH`| `~   0.00 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/41) and all future tips to the issue.

**Comment by gre** [comment]
MEH

**Comment by chaintip** [comment]
Nice work @gre! Your pull request has been merged and the [bounty](http://github.chaintip.org/chaintip/bounties/issues/41) of `0 BCH`| `~   0.00 USD` will be sent to your wallet, once you link it with chaintip.

**Comment by gre** [comment]
🤣

**Comment by dagurval** [comment]
hahaha, oh well, thanks for the fix. I'll be happy send you my original bounty of 0.04628 BCH if you provide me with an address :-)

**Comment by gre** [comment]
it's ok don't worry =)

**Pull request merged**
