### PR TITLE
LL-3449 (Swap/History) Add warning about swaps not being synced

### PR DESCRIPTION
**Pull request by juan-cortes**
Screenshot 2021-06-08 at 15 37 14
Since we are currently not exporting the swap operation history to mobile and there is no mechanism of syncing the two, add a disclaimer on the history page so the user doesn't expect it to be synced between devices. Also includes a small design rework of the sections to be more aligned with the transaction history throughout the app.

### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-3449

### Parts of the app affected / Test plan

-  Launch LLD on an app.json that does have swap history, compare to the screenshot.
-  It should not show if there are no operations.

### CODE REVIEW

**Review by haammar-ledger — DISMISSED** [review]

**Review by Arnaud97234 — APPROVED** [review]
Qa OK.
✅ 
Some screenshots need to be updated

**Comment by juan-cortes** [comment]
Why does it want screenshot changes for things I did not touch?

**Comment by juan-cortes** [comment]
Rebased to make ci run again, I'm not updating the screenshots suggested because it's wrong. If it fails again, I suggest we merge anyway, all suggested screenshots have nothing to do with what I changed (not saying there aren't screenshots that haven't changed, but the ones suggested certainly not)

**Comment by gre** [comment]
still lint issue @juan-cortes

**Comment by juan-cortes** [comment]
Merged develop here to see if screenshots get fixed, otherwise will need to look again

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
looks safe to merge as we mostly fixed snapshots.

**Pull request merged**
