### PR TITLE
add a max spendable banner to send flow

### PR DESCRIPTION
**Pull request by valpinkman**
still waiting for a bump of live-common to retrieve the max spendable value

### Type

Improvement

### Context

LL-2317

### Parts of the app affected / Test plan

Send Flow

Electron 2020-03-24 at 17 11 55@2x

### CODE REVIEW

**Comment by gre** [comment]
you can try it with https://github.com/LedgerHQ/ledger-live-desktop/pull/2754

**Comment by valpinkman** [comment]
image

**Comment by valpinkman** [comment]
removed the learn more link

**Comment by valpinkman** [comment]
image

**Comment by gre** [comment]
For tezos this have nothing to do with the delegation state

**Comment by gre** [comment]
@Arnaud97234  what really matter for XTZ is what address you have set. if it's a new one VS an old one. can you compare the result of both?

@valpinkman please bump live-common to `12.7.4-alpha.0` for arnaud to test on these, other coins (than XTZ) should be fixed.

**Comment by Arnaud97234** [comment]
@gre 
- Sending to an New address: Max spendable = Send Max
xtzToNewAddress

- Sending to an Old address: Max spendable < Send Max
xtzToOldAddress

**Comment by gre** [comment]
status: i still need to provide a fix for some of the issues mentioned here. i'll try to address xtz but i don't  really get what's wrong. i'll find 🤞

**Comment by gre** [comment]
let's check if all of these are fixed 🤞  @Arnaud97234

**Comment by gre** [comment]
@valpinkman v12.8.0-alpha.1

**Comment by gre** [comment]
i'm taking a look

**Comment by gre** [comment]
@Arnaud97234 fixed!

**Comment by gre** [comment]
from perf perspective, maybe we should use some debouncing, i wonder if perf is great, it seems to lag each keystroke. let's rediscuss next week

**Comment by gre** [comment]
@Arnaud97234 this should works again but we'll wait the merge of https://github.com/LedgerHQ/ledger-live-desktop/pull/2771 ideally

**Comment by gre** [comment]
ok good now!

**Pull request merged**
