### PR TITLE
LL-9209 Remove Solana from experimental and add it to supported currencies

### PR DESCRIPTION
**Pull request by ghost**
## 🦒 Context (issues, jira)

https://ledgerhq.atlassian.net/browse/LL-9209

Solana has a GO for production. :rocket: 
This is the last step to enable it as a supported currency.

Also make the EXPERIMENTAL_CURRENCIES toggle a bit more generic and easy to update.

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

### CODE REVIEW

**Comment by haammar-ledger** [comment]
On HODL for a while to confirm infra is stable.

**Review by OlivierFreyssinet — APPROVED** [review]

**Review by gre — APPROVED** [review]

**Pull request merged**
