### PR TITLE
LL5461 - fix countervalue decimals in send flow summary

### PR DESCRIPTION
**Pull request by machard**
https://ledgerhq.atlassian.net/browse/LL-5461

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]

**Review by ychen-ledger — DISMISSED** [review]
Validated with: 

- MacOs Big Sur version 11.4
- Ledger live 2.26.1
- Eth/BTC

**Review by achabrolin-ledger — APPROVED** [review]

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
Hey @machard , please find with resolved conflicts, we have steps 2 network fees in countervalue contains 3 decimals now, please see with ETH/BTC:
Screenshot 2021-08-11 at 13 43 25
Screenshot 2021-08-11 at 13 48 18

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
Hey @machard, please find below, Cosmos in counter value 3 decimals in steps Summary😔, with ETH and BTC is works well
Screenshot 2021-08-11 at 16 41 51

**Review by ychen-ledger — APPROVED** [review]
Validated with:

- MacOs Big Sur version 11.4
- Ledger live 2.32.2
- Eth/BTC/Atom/Dot/BSC

**Pull request merged**
