### PR TITLE
LL-6691 - remove stratis from supported currencies

### PR DESCRIPTION
**Pull request by machard**
https://ledgerhq.atlassian.net/browse/LL-6691

### CODE REVIEW

**Review by hzheng-ledger — APPROVED** [review]
looks good to me

**Comment by gre** [comment]
CI still failing mmh

**Review by juan-cortes — APPROVED** [review]
aaaand it's gone

**Comment by gre** [comment]
@machard could you merge develop in and also remove the line

```
  if (currencies.some(c => c.id === "stratis")) errors.push(new StratisDown2021Warning());
  ```
  
  that we have in one component?

thanks

**Review by juan-cortes — APPROVED** [review]

**Comment by gre** [comment]
@machard conflicts. thx

**Review by juan-cortes — APPROVED** [review]

**Comment by gre** [comment]
CI failing. @machard  :sorry:

**Pull request merged**
