### PR TITLE
LL-4426 (Onboarding): fix issue on analytics tracking and language

### PR DESCRIPTION
**Pull request by LFBarreto**
(Onboarding): fix issue on analytics tracking and language
### Type

Bug Fix
### Context

[LL-4426]
### Parts of the app affected / Test plan

Analytics during first onboarding should work properly now

[LL-4426]: https://ledgerhq.atlassian.net/browse/LL-4426

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Review by juan-cortes — DISMISSED** [review]
Nice catch on the analytics thingie, it was indeed waiting for onboarding completion rather than the actual analytics consent, this is better.

**Review by Arnaud97234 — DISMISSED** [review]
Ok: tracking events now have a language attribute.
✅

**Comment by gre** [comment]
@LFBarreto there is a conflict which indicates it was done similarly somewhere else?

**Comment by LFBarreto** [comment]
> @LFBarreto there is a conflict which indicates it was done similarly somewhere else?

yeah there was an issue in the lang switcher on the onboarding page i fixed it better with the activation of zh translations my bad :bow:

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
