### PR TITLE
Add Native Segwit support

### LINKED ISSUE #1051: Bitcoin bech32 addresses
The application should supports BTC bech32 addresses.

More information:
https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

### LINKED ISSUE #1842: Bech32 Sendability
- [x] I have checked this feature was not yet requested.

There is a similar issue open (https://github.com/LedgerHQ/ledger-live-desktop/issues/1051), but that is about Bech32 integration, this feature request is about Bech32 sendability, which is a simple non-controversial request.

#### Part of the application

Address parsing.

#### Reward

I'd like to also offer ~0.1BTC reward, which will be a Wasabi coinjoin output to whoever implements it here and get his implementation merged.

### PR DESCRIPTION
**Pull request by gre**
🍾Native Segwit (bech32)

Capture d’écran 2019-05-27 à 11 46 19

Shipping it as an experimental feature for now

Capture d’écran 2019-05-27 à 17 53 44

### Type

feature

### Context

Fixes #1842 Fixes #1051 

### Parts of the app affected / Test plan

- not enabling Native Segwit must not show you native segwit accounts in scan accounts
- enabling Native Segwit will allow to scan Native Segwit accounts, if there are some. In `84'/0'/x'` path. the new accounts that can be created are both on Segwit and Native Segwit because there is a usecase for both (some exchanges don't support sending to native segwit).
- disabling Native Segwit after importing some native segwit accounts should be allowed and does not break them
- Synchronisation works fine.
- Receive flow works fine.
- Send flow works fine. Can send from native segwit to legacy. Can send from native segwit to segwit. Reverse to be tested as well.

### CODE REVIEW

**Comment by gre** [comment]
Noticed the same glitch @Arnaud97234 , probably a bug in libcore, I'll report back .

**Comment by KhalilBellakrid** [comment]
@gre @Arnaud97234 I tried with some infos that Gaëtan gave me and I don't reproduce, @Arnaud97234 could you please provide your xpub (testnet) ?

**Comment by gre** [comment]
it seems to be a temporary glitch after doing a tx @KhalilBellakrid

**Comment by KhalilBellakrid** [comment]
I adapted the optimistic update to native Segwit transactions: https://github.com/LedgerHQ/lib-ledger-core/pull/229

**Pull request merged**
