### PR TITLE
[LIVE-1387]: More generic warning message when apps are being installed/updated/deleted

### PR DESCRIPTION
**Pull request by alexandremgo**
## 🦒 Context (issues, jira)

[LIVE-1387](https://ledgerhq.atlassian.net/browse/LIVE-1387?atlOrigin=eyJpIjoiN2E0ZjIwODAxMTg4NDA0YzgyOTQ5YjI4MTJhMDIyYWMiLCJwIjoiaiJ9)

## 💻  Description / Demo (image or video)

<details>
  <summary>Solution</summary>

bugfix-live-1387-solution

</details>

## 🖤  Expectations to reach

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

### CODE REVIEW

**Comment by alexandremgo** [comment]
Following discussion on snapshot error, we'll ignore the error for this PR

**Comment by alexandremgo** [comment]
Build for desktop: [here](https://github.com/LedgerHQ/ledger-live-build/actions/runs/2194130500)

**Review by juan-cortes — COMMENTED** [review]
lgtm but checks are failing https://github.com/LedgerHQ/ledger-live-desktop/runs/6094994764?check_suite_focus=true#step:9:107

**Comment by alexandremgo** [comment]
It has the correct snapshots now 🔥

**Comment by juan-cortes** [comment]
Seems weird that we are a dding tests for other things here, but I guess it's fine for the bugfix paradigm

**Review by juan-cortes — APPROVED** [review]

**Pull request merged**
