### PR TITLE
LL-4514 - Wording for ledger status

### PR DESCRIPTION
**Pull request by juan-cortes**
image

### Type

Wording

### Context
https://ledgerhq.atlassian.net/browse/LL-4514

### CODE REVIEW

**Comment by juan-cortes** [comment]
Added support for the help drawer on the spectron specs, since the wording here affects the feature and it wasn't covered. We should probably improve our tests like this whenever we touch a part of the app that's not covered 🤔 
cc @gre

**Comment by gre** [comment]
@juan-cortes test CI fails.


for the test code, i have a feeling that everytime we do this:

```
await app.client.pause(400)
```

we should replace by something like

```
await waitFor_some_UI_To_Refresh()
```

with a specific condition to wait for

**Comment by juan-cortes** [comment]
If you look at the screenshot diff it seems like there's a row that has a hover/active effect, not related to the pr's code at all. 
I bet running it again would work 🤔

**Comment by juan-cortes** [comment]
> @juan-cortes test CI fails.
> 
> for the test code, i have a feeling that everytime we do this:
> 
> ```
> await app.client.pause(400)
> ```
> 
> we should replace by something like
> 
> ```
> await waitFor_some_UI_To_Refresh()
> ```
> 
> with a specific condition to wait for

You are probably right

**Comment by juan-cortes** [comment]
🤷🏼‍♂️ @machard any clue what can be causing the hover effect?

**Comment by machard** [comment]
I don't understand why it works on develop but not in here :/

**Comment by machard** [comment]
I think @valpinkman will stabilize accounts tests

**Comment by valpinkman** [comment]
@machard @juan-cortes the PR is ready, just awaiting validation

**Review by valpinkman — DISMISSED** [review]

**Review by Arnaud97234 — CHANGES_REQUESTED** [review]
@juan-cortes In French, desc is still "Learn crypto". Translation needed ?

**Review by Arnaud97234 — DISMISSED** [review]

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
For translation we should not update them. We should not test a feature but in English @Arnaud97234 
Translation get invalidated when a feature is merged.

**Comment by gre** [comment]
@juan-cortes conflicts

**Comment by juan-cortes** [comment]
> @juan-cortes conflicts

Should be fine now, I didn't update the test though since @valpinkman was working on removing the getters,
it can addressed on a separate pr

**Comment by gre** [comment]
tests are failing 🌊

**Comment by juan-cortes** [comment]
Yeah things tend to fail went left unmerged for weeks at a time :trollface: hopefully it will work now

**Comment by gre** [comment]
shipped through mashup PR

**Pull request closed without merging**
