### PR TITLE
LL-6731 regions, dates, time and currencies

### PR DESCRIPTION
**Pull request by OlivierFreyssinet**
## 🦒 Context (issues, jira)

[LL-6731]

Added a new field `locale` in the settings that is set when the user changes the region. Its value will be a locale.
`localeSelector` has been modified to use this field while taking into account old existing settings and a new logic to fallback to the language setting.

The existing `region` field in the settings hasn't been removed as it's used for segment analytics we need to handle users' existing saved settings.

- Numbers formatting: Almost all numbers in the app are already formatted using localeSelector
- Currencies formatting: same
- Dates & time formatting: dates are formatted using moment.js so the logic to init/update moment's locale has been changed. (It was previously using the language setting)

## 💻  Description / Demo (image or video)

- From a user's perspective, the region settings are now completely decoupled from the language settings so they can choose whatever region they want regardless of the language settings.
- All dates, numbers, times and currencies are now formatted using the locale defined by the region settings.
- The description of the region settings has been modified (using the text from the spec) to better explain what this setting does.

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

[LL-6731]: https://ledgerhq.atlassian.net/browse/LL-6731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by LFBarreto — DISMISSED** [review]
:rocket:

**Review by LFBarreto — CHANGES_REQUESTED** [review]

**Review by LFBarreto — DISMISSED** [review]

**Review by LFBarreto — DISMISSED** [review]

**Review by LFBarreto — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]
Nice, this is long overdue 🚀

**Review by nabil-brn — DISMISSED** [review]
✔️ QA-ed

**Review by nabil-brn — APPROVED** [review]

**Pull request merged**
