### PR TITLE
[LL-5137] change CTA account header

### PR DESCRIPTION
**Pull request by henri-ly**
### Type

UI Polish

### Context

https://ledgerhq.atlassian.net/browse/LL-5137

### Parts of the app affected / Test plan

All account header

### CODE REVIEW

**Review by machard — DISMISSED** [review]

**Review by gre — DISMISSED** [review]

**Review by Arnaud97234 — APPROVED** [review]
Currently the user needs to Accept Changelly T&C's to be able to access the Swap feature from an account page.

It will be fixed in a future PR. So we can merge this one.

**Comment by gre** [comment]
ok,  i'll merge https://github.com/LedgerHQ/ledger-live-desktop/pull/3760 first and i'll manage the screenshot conflict & merge this one too

**Review by Arnaud97234 — DISMISSED** [review]
Currently the Swap CTA is missing on an account page until user go to theglobal swap entry (sidebar) and accept T&C's. @cthepot-ledger Will create a task to solve the issue in the future.

**Comment by JunichiSugiura** [comment]
Is it only me getting diffs in `yarn.lock` after running `yarn` ?

**Comment by gre** [comment]
@JunichiSugiura i'm committing yarn.lock update as part of this push. i'll then wait snapshot to regen.

**Pull request merged**
