### PR TITLE
LIVE-1928 LIVE-1776 - Add Spanish (ES) and Chinese (ZH) to pushed languages

### PR DESCRIPTION
**Pull request by OlivierFreyssinet**
With this change, we add more languages (Chinese and Spanish) to the list that makes it easy for existing users and new users to switch to their OS language:
- New users get that language by default when first launching LLD.
- Existing users that use the app in another language (english typically) get prompted with a modal telling them that their OS language is available.

## 🦒 Context (issues, jira)

[LIVE-1928]
[LIVE-1776]

#### new users:

https://user-images.githubusercontent.com/91890529/164006563-0eef5118-83bf-470c-87e0-42aec001b951.mov

#### existing users (simulating "existing user" by doing a 1st start with the OS language in English and then after changing the OS language to Spanish, restarting LL):

https://user-images.githubusercontent.com/91890529/164007283-2bd6bb7e-9bfa-4392-b83a-03a0fddcd92f.mov

## 🖤  Expectations to reach

- Discoverability for new users (fully supported languages):
    1. Uninstall LL
    2. Switch OS language to Spanish or Chinese (fully supported languages)
    3. Install LL, launch it
    4. LL should be in the system's language

- Discoverability for existing users
   1. Uninstall LL
   2. Switch OS language to English
   3. Install LL, launch it, go through onboarding
   4. Quit LL, switch OS language to Spanish or Chinese
   6. Launch LL
   7. LL should prompt a dialogue asking the user to switch the language to the OS language

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

[LIVE-1928]: https://ledgerhq.atlassian.net/browse/LIVE-1928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-1776]: https://ledgerhq.atlassian.net/browse/LIVE-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nparigi-ledger — APPROVED** [review]

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
hey @ofreyssinet-ledger could you have a resolve for conflicts? 🙏

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
hey @ofreyssinet-ledger👋🏼, could you have a resolve of all conflicts?🙏

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
@ofreyssinet-ledger MacOs build failed, could u take a look?😔

**Review by ychen-ledger — CHANGES_REQUESTED** [review]
hey @ofreyssinet-ledger👋🏼  ticket reopened as comment in https://ledgerhq.atlassian.net/browse/LIVE-1928

**Review by LFBarreto — APPROVED** [review]

**Comment by LFBarreto** [comment]
Tested on linux + spanish:
new users flow :heavy_check_mark: 
existing users :heavy_check_mark: 

localhost_8080_webpack_index html_theme=null appLocale=es
localhost_8080_webpack_index html_theme=null appLocale=es_2

**Review by LFBarreto — APPROVED** [review]

**Review by ychen-ledger — APPROVED** [review]
Validated on: 

- LLD 2.41.3-sha.d134af6194614ae7b5eb8c783e225d4d062ffec7
- MacOS/Windows with remove app.json all times

**Pull request closed without merging**
